export type Gate = {"number": number, "name": string, "center": string, "circuit": string, "core": string, "clean": string, "listen": string, "keywords": string[]};

export const gates: Gate[] = [
  {
    "number": 1,
    "name": "Self-Expression",
    "center": "G Center",
    "circuit": "Individual",
    "core": "Gate 1 is the gate of the creative self. This energy wants to create in a big, unmistakable way - with a style that is entirely its own. It is not creating for an audience in the traditional sense. It is creating because it has to, because the self demands to be expressed, because withholding the creative impulse is a kind of suffocation. Gate 1 is determined to draw attention, not out of vanity, but because bold creative presence is the most natural form of its existence.",
    "clean": "At its highest, Gate 1 is a creative force that opens something up in the people who encounter it. There is no apology for its scale. It does not shrink to be palatable. The work it makes carries a signature so specific and alive that it cannot be mistaken for anyone else's. This is the creative self in full frequency.",
    "listen": "Gate 1 songs carry bold creative presence. They feel like someone making something that could only have come from them - not derivative, not trend-following, genuinely original in tone, style, or emotional honesty. You might feel this gate in a vocal choice that is unlike anything you have heard, or in a production that breaks the expected rules of its genre without sounding chaotic. There is a \"look at what I made\" energy in Gate 1 music that is not arrogant - it is the natural confidence of genuine creative self-expression. Songs that feel like a declaration of artistic identity live here.",
    "keywords": [
      "Creativity",
      "Self-expression",
      "Originality",
      "Bold presence",
      "Making",
      "Artistic identity",
      "Uniqueness",
      "Creative self",
      "Visibility",
      "Authenticity"
    ]
  },
  {
    "number": 2,
    "name": "Receptivity / Higher",
    "center": "Knowledge G Center",
    "circuit": "Individual",
    "core": "Gate 2 is the driver of the self - the energy that moves the soul forward. It is paradoxical: people with Gate 2 often have little clear awareness of their own direction while being naturally skilled at guiding others toward theirs. This is the gate of higher knowledge received in a receptive, feminine way. It is not acquired through study. It comes through stillness, openness, and trust in what the self is already moving toward even when the destination is invisible.",
    "clean": "Gate 2 at its highest is a quiet but unmistakable compass. It does not need to announce its direction loudly. It holds the knowing of where things are going and allows others to be oriented by that presence. There is a receptive quality to it that is not passive - it is actively open, still enough to receive, grounded enough to hold what it receives.",
    "listen": "Gate 2 songs carry a quality of being guided toward something. They feel like direction given gently. The energy is feminine without being soft - assured, knowing, open. Songs with a quality of wisdom that arrives without explanation. Music that has a sense of \"you do not need to understand this yet, just follow it.\" Melodies that feel like they are leading somewhere you trust.",
    "keywords": [
      "Receptivity",
      "Inner knowing",
      "Guidance",
      "Direction",
      "Higher knowledge",
      "Feminine wisdom",
      "Trust",
      "Soul navigation",
      "Stillness",
      "The driver"
    ]
  },
  {
    "number": 3,
    "name": "Ordering",
    "center": "Sacral",
    "circuit": "Individual",
    "core": "Gate 3 is the energy of ordering and completion - the force that brings chaos toward resolution. When a project or process has been initiated without a clear path, Gate 3 is what helps organize the solution so it can actually come to pass. This is not the energy of starting things. It is the energy that steps into an existing mess and figures out how to move it toward closure. It lives in the Sacral, so it does this work with life force and response rather than mental strategy.",
    "clean": "At its best, Gate 3 is the calm in the middle of a mess. It knows something is taking shape even when everything looks chaotic, and it works patiently toward the solution without forcing the timeline. The order it creates tends to be elegant - not imposed from outside, but discovered from within the situation itself.",
    "listen": "Gate 3 songs often carry a quality of resolution arriving after chaos. Songs where the musical structure itself moves from disorder toward something that clicks into place. The transition from verse to chorus might feel like the tension releasing. Lyrically, these songs often deal with finding the thread, sorting through confusion, or arriving at a hard-won sense of clarity or completion. Songs about finishing, resolving, and finally getting something done.",
    "keywords": [
      "Ordering",
      "Completion",
      "Resolution",
      "Organizing chaos",
      "Mutation",
      "Finding the path",
      "Sacral response",
      "Individual process",
      "Difficulty to beauty",
      "Closure"
    ]
  },
  {
    "number": 4,
    "name": "Answers",
    "center": "Ajna",
    "circuit": "Collective",
    "core": "Gate 4 is the drive to find the answer - not just any answer, but the one answer. It is a Collective gate, which means its formulas and mental solutions are meant to be shared for the benefit of others, not kept private. But the answers Gate 4 generates are technically possibilities, not certainties. The gate does not always know the difference. This is where its shadow lives: the insistence that a possibility is an absolute truth.",
    "clean": "Gate 4 at its highest holds its formulas lightly - as offerings, not mandates. It shares mental solutions as gifts. It says \"here is a possibility that might help\" rather than \"here is the truth.\" The curiosity is alive without becoming insistence. The mental drive creates real value when it is in service to exploration rather than proving.",
    "listen": "Gate 4 songs often carry a question-and-answer structure - a restless searching quality followed by a moment of arrived clarity. Clever, intricate lyrics that feel like they are working something out. Songs that feel mentally stimulating, as if the artist is solving a problem in real time through the song itself. The satisfaction of a well-constructed argument set to music. Intellectually rich music that also has an emotional core.",
    "keywords": [
      "Answers",
      "Mental formulas",
      "Possibility",
      "Logic",
      "Searching",
      "Collective solutions",
      "Mental pressure",
      "Formulation",
      "Intellectual drive",
      "Sharing ideas"
    ]
  },
  {
    "number": 5,
    "name": "Fixed Rhythms /",
    "center": "Patterns Sacral",
    "circuit": "Collective",
    "core": "Gate 5 carries a mechanical need for fixed rhythm. This is the energy of habits, routines, and the unconscious drive toward pattern in daily life. People working with Gate 5 energy need rhythm not as discipline but as biological necessity - the body knows what time it wants to eat, what time it wants to sleep, what order it wants to move through the day. When that rhythm is honored, everything works. When it is disrupted, the whole system feels off.",
    "clean": "Gate 5 at its best is someone who has found their rhythm and honors it without making it a prison. The routine serves the person, not the other way around. There is a quality of ease and sustainability to how they move through their days - nothing forced, nothing frantic.",
    "listen": "Gate 5 songs are often characterized by steady, reliable beats and repetitive musical structures that feel anchoring rather than boring. The music has a groove that the body wants to settle into and stay. Think of music you put on when you are cooking the same meal you make every Sunday, or the playlist you play every morning before you start working. Songs with mechanical rhythms, reliable four-on-the-floor beats, or chants that repeat. Music your body knows.",
    "keywords": [
      "Rhythm",
      "Routine",
      "Habit",
      "Fixed patterns",
      "Mechanical repetition",
      "Consistency",
      "Anchoring",
      "Daily life",
      "Biological timing",
      "Collective rhythm"
    ]
  },
  {
    "number": 6,
    "name": "Friction",
    "center": "Solar Plexus",
    "circuit": "Tribal",
    "core": "Gate 6 is the gate of friction and intimacy - the energy that governs who is allowed into your inner circle and who is kept out. It operates at the boundary between self and other, deciding whether to merge or maintain distance. On a deeper level, it connects to sexual and reproductive energy - the question of who you let in close enough to create something with, literally or metaphorically. This gate discriminates between emotional connection and mere proximity.",
    "clean": "Gate 6 at its highest is a beautifully calibrated filter. It knows who is kin and who is not, not by logic but by feeling. The intimacy it allows in is real and protected. The friction it creates at the boundary serves a purpose - it keeps the inner circle genuine and the outer circle honest.",
    "listen": "Gate 6 songs feel intimate in a way that is not entirely comfortable. There is tension in them - the push-pull of someone deciding whether to let another person in. Songs about desire, boundaries, sexual tension, \"are you mine or not,\" the vulnerability of closeness. The emotional charge of Gate 6 music is specific: it is not generalized longing (that is more Gate 30). It is the particular energy of a specific connection and the question of whether it is safe to let it fully land.",
    "keywords": [
      "Friction",
      "Intimacy",
      "Boundaries",
      "Inner circle",
      "Discernment",
      "Sexual energy",
      "Tribal bonding",
      "Emotional gating",
      "Merger",
      "Selection"
    ]
  },
  {
    "number": 7,
    "name": "Role Of The Self",
    "center": "G Center",
    "circuit": "Collective",
    "core": "Gate 7 is the energy of natural leadership - but leadership that must be recognized before it can be effective. This is not the kind of leadership that announces itself and demands followers. It is the kind that is called upon, invited into the role, recognized by others as the guide they need. Gate 7 can move across a wide range of leadership styles depending on the channel it works with and the context it finds itself in - from democratic to authoritative - but in all cases, its power comes through recognition.",
    "clean": "Gate 7 at its highest is the leader who does not need to chase authority. They show up, and the role comes to them. There is a grace to it - they serve something larger than their own ego, and because of that, others naturally orient toward them.",
    "listen": "Gate 7 songs often carry an air of natural authority. Songs where the artist is clearly the guide, the narrator, the leader of the experience - and you trust them. Leadership anthems, songs about stepping into a role, music that feels like it is creating a path for you to walk. There is a quality of collective orientation to these songs - they feel like they are pulling a group in a particular direction rather than speaking to a single listener.",
    "keywords": [
      "Leadership",
      "Recognition",
      "Role",
      "Service",
      "Natural authority",
      "Collective guidance",
      "Democracy",
      "Influence",
      "Direction",
      "Being called"
    ]
  },
  {
    "number": 8,
    "name": "Contribution",
    "center": "Throat",
    "circuit": "Individual",
    "core": "Gate 8 is the energy of contribution - making a statement, being an example, doing something that stands out and leaves a mark. It draws attention to itself through the telling of profound truths and the living of a distinct, visible style. Gate 8 is not trying to blend in. It is designed to be different, to show up boldly, to be the proof of concept for a different way of doing things. It needs to express its own unique energy, and when it does, it creates something others can actually learn from.",
    "clean": "Gate 8 at its highest is the person who shows up as themselves, fully, and whose very presence is instructive. Their style, their work, their way of moving through the world is a living demonstration of something real. People pay attention because there is something worth paying attention to.",
    "listen": "Gate 8 songs feel like statements. Songs that make you want to show people - \"have you heard this?\" Songs where the artist is being exactly who they are with no apology, and the boldness of that is the whole point. Songs about being a living example, making your mark, being seen for what you actually are. There is an \"I have something to say and it matters\" quality to Gate 8 music that is distinct from the softer, more vulnerable Gate 12.",
    "keywords": [
      "Contribution",
      "Bold statement",
      "Example",
      "Visibility",
      "Unique style",
      "Attention",
      "Truth-telling",
      "Standing out",
      "Creative identity",
      "Making a mark"
    ]
  },
  {
    "number": 9,
    "name": "Focus",
    "center": "Sacral",
    "circuit": "Collective",
    "core": "Gate 9 is the power to remain focused over time. This is not concentration in a single-pointed, obsessive way - it is more like sustained, moving attention. Gate 9 is always in motion, always experimenting and repeating, but the focus does not break. It is the energy of refining something through repeated attempts, learning from each iteration without losing the thread. This gate is driven to test and repeat, which is what builds mastery over time.",
    "clean": "Gate 9 at its highest is a master of the process of mastery. It knows how to stay in the work even when progress is slow, how to keep refining without losing enthusiasm, how to build something meaningful through the accumulation of small, focused efforts.",
    "listen": "Gate 9 songs often carry a quality of deliberate, sustained effort. The production is layered - you hear details on repeat listens that you missed the first time. Songs with intricate arrangements, repeated motifs that evolve slightly, music that rewards sustained attention. Songs about repetition as practice, the grind that creates something worthwhile, the pleasure of doing the same thing again and better.",
    "keywords": [
      "Focus",
      "Repetition",
      "Mastery",
      "Sustained effort",
      "Experimentation",
      "Detail",
      "Collective knowledge-building",
      "Sacral drive",
      "Refinement",
      "Process"
    ]
  },
  {
    "number": 10,
    "name": "Behavior Of The Self",
    "center": "G Center",
    "circuit": "Individual",
    "core": "Gate 10 is the gate of self-love and the behavior that flows from it. This is the energy of empowering oneself and others through how one moves through the world - not through words or strategy, but through the lived example of being oneself. Gate 10 carries a consistent energy to love: love of self, love of life, love extended outward to others. When it is aligned, the way this gate behaves in the world naturally empowers everyone around it.",
    "clean": "Gate 10 at its best is radical, embodied self-love. Not affirmations - behavior. How you actually live, how you actually treat yourself, what you actually say yes and no to. When Gate 10 is in its highest frequency, it is one of the most quietly powerful energies in the chart because the behavior itself is the message.",
    "listen": "Gate 10 songs carry the unmistakable frequency of self-acceptance. Self-love anthems, but not shallow ones - songs that have actually done the work of believing in their own worth and you can feel it. Songs that make you want to take better care of yourself not because someone told you to, but because the music made you feel worthy of it. Songs about loving your own nature, walking your own path, refusing to betray yourself.",
    "keywords": [
      "Self-love",
      "Behavior",
      "Empowerment",
      "Love of life",
      "Authenticity",
      "Walking your truth",
      "Individual expression",
      "Self-worth",
      "Quiet power",
      "Living example"
    ]
  },
  {
    "number": 11,
    "name": "Ideas",
    "center": "Ajna",
    "circuit": "Collective",
    "core": "Gate 11 is the gate of ideas - specifically, the sensing energy that gathers and sorts images, impressions, and pieces of story until they form a larger picture. This is not logical idea generation. It is the intuitive piecing together of abstract fragments into something that begins to feel coherent. Gate 11 is the collector of images for the Collective Sensing stream, which means its ideas are meant to eventually become shared stories, frameworks, and ways of making sense of collective experience.",
    "clean": "Gate 11 at its highest is a generator of rich, meaningful stories that help others make sense of their experience. The images and ideas it holds are curated by something deeper than preference - there is a knowing about which pieces belong together. When those pieces come together, the story they create has a quality that feels necessary and true.",
    "listen": "Gate 11 songs feel like entering a dream. They are atmospheric, image-rich, narrative without being linear. Songs that create a world you can walk around in rather than a story you follow from point A to point B. Music that feels like a series of impressions building toward a feeling rather than a conclusion. Storytelling through texture and imagery more than plot. Songs that feel like they are showing you something rather than telling you something.",
    "keywords": [
      "Ideas",
      "Storytelling",
      "Images",
      "Collective sensing",
      "Abstract narrative",
      "Imagination",
      "Piecing together",
      "The bigger picture",
      "Creative overload",
      "Dreamlike"
    ]
  },
  {
    "number": 12,
    "name": "Caution",
    "center": "Throat",
    "circuit": "Individual",
    "core": "Gate 12 is the energy of speaking from the heart - in an individual, vulnerable way. The energy of \"I love you.\" It is careful, which is where the name Caution comes from. This gate does not rush into expression. It holds what it feels until the right moment arrives, and then it speaks with a tenderness that is genuinely moving. It can express itself through shyness because what it holds is truly vulnerable - the direct, individual declaration of care.",
    "clean": "Gate 12 at its highest is the person who knows exactly when and how to say the tender thing. Their declarations are rare enough to carry weight. When they say \"I love you,\" or \"here is what this means to me,\" the person receiving it feels it completely because the timing and the delivery match the depth of what is being communicated.",
    "listen": "Gate 12 songs are the love songs that stop you. Not the grand sweeping ones - the quiet ones. The songs where someone is clearly about to say something that scares them, and they say it anyway. A vocal delivery so raw and specific that it feels like you walked in on something private. Songs with a careful quality to them, like the words were chosen with reverence for their own weight. Shy emotional declarations set to music.",
    "keywords": [
      "Caution",
      "Vulnerability",
      "Love",
      "Tenderness",
      "Individual expression",
      "Timing",
      "Holding back",
      "Letting out",
      "Heart speech",
      "The quiet declaration"
    ]
  },
  {
    "number": 13,
    "name": "Listener",
    "center": "G Center",
    "circuit": "Collective",
    "core": "Gate 13 is the energy of the witness - the one who listens so well that others are drawn to share things they never planned to share. This is a Collective gate, meaning the stories and secrets it collects are not kept for private use. They are held as part of a larger archive of human experience. Gate 13 attracts confession. It creates a field of openness that makes people feel safe enough to say the real thing.",
    "clean": "Gate 13 at its highest holds what it hears with wisdom and discretion. The listening is active and generous. What it has gathered from a lifetime of receiving stories becomes the source of real understanding - not just of other people, but of the human condition as a whole.",
    "listen": "Gate 13 songs create a listening space. They feel like the music itself is receiving you. Songs that make you want to tell the truth, that create the conditions for honesty to arise. Music that holds complexity without judgment - that can sit with contradiction, with pain and joy in the same breath, without rushing toward resolution. Songs you listen to alone, that feel like being truly heard.",
    "keywords": [
      "Listening",
      "Witnessing",
      "Secrets",
      "Stories",
      "Receiving",
      "Collective memory",
      "Openness",
      "Truth-telling",
      "Holding space",
      "Archive"
    ]
  },
  {
    "number": 14,
    "name": "Power Skills",
    "center": "Sacral",
    "circuit": "Individual",
    "core": "Gate 14 is the fuel that powers your direction in life. It carries within it an assurance that material abundance will follow authentic self-expression - that doing what you are actually built to do creates wealth, not poverty. This is not the ambition energy of Gate 54 (which chases material success directly). Gate 14 is the power that comes from being fueled by the right work. When this gate is moving through its correct channel, the sense of empowerment and capability is palpable.",
    "clean": "Gate 14 at its highest is the person whose work feels like a calling and a joy - who is clearly fueled by what they do, not just obligated to it. The abundance they create comes as a natural byproduct of being in the right work, and they know the difference between that and forcing outcomes.",
    "listen": "Gate 14 songs carry a quality of \"I've got this\" that runs deep. Confidence as a bodily state, not a mental decision. Songs about mastery, skill, doing what you were made to do, moving through the world with capability. Music that feels empowering in a grounded, sacral way - not adrenaline, but power. Songs that make you feel competent, resourced, and ready to build something.",
    "keywords": [
      "Power",
      "Skill",
      "Mastery",
      "Material abundance",
      "Fuel",
      "Empowerment",
      "Direction",
      "Individual resource",
      "Capability",
      "Doing what you're built for"
    ]
  },
  {
    "number": 15,
    "name": "Extremes",
    "center": "G Center",
    "circuit": "Collective",
    "core": "Gate 15 is the gate of extreme rhythms - the energy that expresses itself through wild swings in pattern, timing, and behavior. Where Gate 5 needs a fixed rhythm, Gate 15 needs rhythm that constantly changes. People with Gate 15 are always in the process of finding their rhythm, and just when they think they have it, everything shifts. This is not a problem to be solved. It is the nature of the energy. Gate 15 holds the greatest potential range in the bodygraph - from the most regular to the most irregular.",
    "clean": "Gate 15 at its highest embraces the range as its own kind of rhythm. It does not apologize for being inconsistent by conventional standards. Its unpredictability becomes a kind of grace - the ability to meet life at whatever extreme it is currently offering and be fully present there.",
    "listen": "Gate 15 songs often have unpredictable structures. Time signature changes, unexpected key shifts, songs that are tender and then explosive, songs that start as one thing and become another. Music that feels like a full range of human experience compressed into one track. Songs that take you somewhere you did not expect to go. Anything that defies a consistent groove in favor of a dynamic range.",
    "keywords": [
      "Extremes",
      "Rhythm",
      "Range",
      "Inconsistency",
      "Wildness",
      "Unpredictability",
      "Collective humanity",
      "Embracing the swing",
      "No fixed pattern",
      "Dynamic living"
    ]
  },
  {
    "number": 16,
    "name": "Skills",
    "center": "Throat",
    "circuit": "Collective",
    "core": "Gate 16 is the \"just do it\" gate. It is the energy of enthusiasm for life and a natural talent that expresses itself through doing, not planning. Gate 16 does not wait until it knows how to do something. It starts, and figures out the details as it moves. This creates a kind of effortless-looking mastery that others read as natural talent - which it is, but only because Gate 16 is willing to express before it is ready.",
    "clean": "Gate 16 at its highest is the person who says yes and then figures out the rest. There is a quality of throwing yourself in with genuine enthusiasm, trusting that the skill will develop in the doing. When this works - and it usually does - the result has a vitality that planned, perfected work often lacks.",
    "listen": "Gate 16 songs feel enthusiastic and alive. There is a \"let's go\" energy to them. Songs that do not overthink their own premise. Music that throws itself into the experience without hedging. Often upbeat, high-energy tracks that feel like the artist was having genuine fun. Songs about diving in, going for it, natural talent expressed with abandon. Music that sounds easy even if it was not.",
    "keywords": [
      "Skills",
      "Enthusiasm",
      "Just do it",
      "Natural talent",
      "Action",
      "Expression",
      "Collective sharing",
      "Diving in",
      "Vitality",
      "Doing before knowing"
    ]
  },
  {
    "number": 17,
    "name": "Opinions",
    "center": "Ajna",
    "circuit": "Collective",
    "core": "Gate 17 is the energy of opinions - specifically, the energy that generates possibilities and perspectives rather than fixed truths. Gate 17 offers a view. It says \"here is what might work, here is a pattern I noticed, here is a new way to look at this.\" At its best, it holds those opinions lightly, as contributions to a collective conversation rather than pronouncements from on high. It is genuinely curious about whether its formulas will prove out.",
    "clean": "Gate 17 at its highest is one of the most generative energies for collective understanding. It sees patterns before others do and offers them as openings rather than conclusions. \"What if it worked this way?\" is Gate 17 at its best - a question disguised as an opinion that cracks something open for everyone.",
    "listen": "Gate 17 songs often have a provocative or thought-shifting quality. Songs that make you look at something differently. Lyrics that propose a framework or angle you had not considered. Music with a questioning edge - not doubt (that is Gate 63), but the kind of curiosity that opens a door. Songs that feel like they are offering you something to think about rather than something to feel. Intellectual music with an emotional hit.",
    "keywords": [
      "Opinions",
      "Possibilities",
      "Perspective",
      "Patterns",
      "Collective formulas",
      "Questioning",
      "\"What if\"",
      "Proposing",
      "Logic",
      "Opening minds"
    ]
  },
  {
    "number": 18,
    "name": "Correction",
    "center": "Spleen",
    "circuit": "Collective",
    "core": "Gate 18 is the logical impulse to improve - to identify what is not working and offer a better way. This is corrective energy in service of the collective good. It wants to save time, avoid mistakes, bring joy into areas where inefficiency has created suffering. Gate 18 is not critical for the sake of being critical. It is trying to help. But the key condition on this energy is that it must be recognized and invited before it can be effectively expressed.",
    "clean": "Gate 18 at its highest waits until it is asked. The discernment is just as sharp, but it is offered as a gift - \"I see what could work better here, and I want to share it because I think it will genuinely help.\" The correction lands because it was invited, and it creates improvement that everyone benefits from.",
    "listen": "Gate 18 songs often carry a quality of \"here's what actually works.\" Songs about optimization, process, refining something toward its better form. Music that is technically excellent - not just emotionally resonant, but crafted with a precision that reveals the care that went into getting it exactly right. Songs that fix something. Songs that you listen to and think \"yes, that is how this should have been said.\"",
    "keywords": [
      "Correction",
      "Improvement",
      "Logic",
      "Discernment",
      "Optimization",
      "Better way",
      "Critique",
      "Joy through efficiency",
      "Spleen knowing",
      "Collective service"
    ]
  },
  {
    "number": 19,
    "name": "Wanting",
    "center": "Root",
    "circuit": "Tribal",
    "core": "Gate 19 is the energy that wants and needs community - with an urgency that feels physical. This gate presses for unrestricted access to the people, resources, and connections that make up the tribe. It is deeply sensitive to the emotional state of those around it, which can make it feel both hyper-attuned and easily overwhelmed. The wanting here is not personal ambition - it is the wanting of belonging, of being part of something, of having needs met within a system of mutual support.",
    "clean": "Gate 19 at its highest is exquisitely attuned to the needs of its community - not just its own, but others'. It senses what is needed before anyone says it. This sensitivity becomes a gift rather than a burden when it is directed by genuine care rather than anxiety.",
    "listen": "Gate 19 songs are about longing for connection. The particular ache of wanting to belong, to be with your people, to be near the ones who understand you. These songs can feel tender and raw. They carry a sensitivity that is not always comfortable. Songs about community, family, need, and the vulnerability of wanting access to people you love. Music that makes you want to call someone.",
    "keywords": [
      "Wanting",
      "Sensitivity",
      "Community",
      "Belonging",
      "Need",
      "Tribal longing",
      "Access",
      "Attunement",
      "Rootedness",
      "Connection hunger"
    ]
  },
  {
    "number": 20,
    "name": "Now / The Present",
    "center": "Throat",
    "circuit": "Individual",
    "core": "Gate 20 is the energy of the present moment - the only moment Gate 20 can actually see. This is not a gate of planning or reflection. It is built to be completely absorbed in what is happening right now. People moving through Gate 20 often have no idea what they are going to say or do until the moment it happens. They move quickly when they are following their authority, and the speed is right because the action is fully present rather than calculated.",
    "clean": "Gate 20 at its highest is genuinely, fully here. There is a quality of undistracted presence that is rare and magnetic. Actions that emerge from this gate in its highest expression have a clarity and decisiveness that others recognize as authority - because they are. The body knows what to do, and it does it.",
    "listen": "Gate 20 songs have a NOW quality. An immediacy. Songs that feel like they are happening in real time rather than being remembered or anticipated. Spontaneous-sounding energy, even in carefully produced music. Songs with a spoken-word quality or a directness that does not hedge. Music that feels urgent not because of adrenaline, but because of presence. Songs that wake you up to where you actually are.",
    "keywords": [
      "Now",
      "Presence",
      "Immediacy",
      "Spontaneity",
      "Action",
      "Contemplation",
      "Individual expression",
      "The moment",
      "No plan",
      "Awareness"
    ]
  },
  {
    "number": 21,
    "name": "Hunter / Huntress",
    "center": "Heart/Ego",
    "circuit": "Tribal",
    "core": "Gate 21 is the Hunter/Huntress energy - the drive to control, acquire, and thrive in the material world. This gate knows what it wants and moves toward it with territorial intensity. It controls where it lives, what it eats, what it needs, what it will and will not accept. Gate 21 is designed for material competence and the willpower to secure resources. This is Ego/Heart energy in its most active, acquisitive form.",
    "clean": "Gate 21 at its highest is the strategic, capable provider - for itself, for its tribe, for its business. The control it exercises is effective because it is applied correctly, to things within its domain and not beyond it. The material drive creates abundance rather than hoarding.",
    "listen": "Gate 21 songs feel territorial and driven. Songs about getting what you came for. \"This is mine.\" Songs about material success, strategic pursuit, the satisfaction of having secured what you need. A focused, purposeful energy - not impulsive, but tracked. Hunting music. Songs that feel like you are moving through the world with intention and the capability to act on it.",
    "keywords": [
      "Control",
      "Hunter",
      "Material drive",
      "Acquisition",
      "Territorial",
      "Willpower",
      "Securing resources",
      "Ego",
      "Tribal provision",
      "Capability"
    ]
  },
  {
    "number": 22,
    "name": "Grace / Openness",
    "center": "Solar Plexus",
    "circuit": "Individual",
    "core": "Gate 22 is the energy of emotional grace - the ability to be individually open to the emotional wishes of the collective. This is a mood-driven gate. When the mood is right, someone carrying Gate 22 can work a room effortlessly, moving through social space with a quality that makes others feel genuinely welcomed and seen. Gate 22 transmits emotionality into individual expression, which means its feelings are infectious in the best sense - others feel what it feels.",
    "clean": "Gate 22 at its highest is the person who is fully, gracefully present when they are present - and fully, unapologetically absent when they are not. The emotional range is wide and deep. The grace that arises when the conditions are right is genuinely beautiful to be around.",
    "listen": "Gate 22 songs carry emotional grace. The kind of music that creates a quality of space - you feel welcome inside it, like the emotional atmosphere is both warm and spacious. Songs that feel like a very good host. Music that transmits mood rather than stating it. Songs where you cannot quite name what makes them so easy to be with. Also songs that are explicitly about social grace - about moving through a room, receiving people, holding emotional space.",
    "keywords": [
      "Grace",
      "Openness",
      "Mood",
      "Emotional presence",
      "Social magnetism",
      "Receptivity",
      "Individual emotion",
      "Transmitting feeling",
      "\"Working the room\"",
      "Warmth"
    ]
  },
  {
    "number": 23,
    "name": "Assimilation",
    "center": "Throat",
    "circuit": "Individual",
    "core": "Gate 23 is the energy of bringing a knowing into expression - of taking an insight that has arrived and integrating it into something that can be communicated clearly. This gate drives you to create and birth new things, to express the insights that are ahead of their time in a way that lands. Gate 23 synthesizes the known and the not-yet-known into something expressible. The insights it carries are often ahead of their time, which means they may not be immediately understood.",
    "clean": "Gate 23 at its highest is a bridge - between the known and the not-yet-known, between its own inner download and the world outside. The communication is clear even when the content is novel. People understand, not just intellectually but by feeling the truth in it.",
    "listen": "Gate 23 songs feel like creative breakthroughs. Songs where you sense the artist just figured something out and is sharing it while it is still fresh. A quality of emerging insight - not fully packaged, but alive. Songs that sound slightly ahead of their moment. Music that synthesizes influences in a way that creates something new and names it clearly. \"I just figured this out and here it is.\"",
    "keywords": [
      "Assimilation",
      "Creative downloads",
      "Insight",
      "New things",
      "Birth",
      "Individual expression",
      "Synthesis",
      "Ahead of time",
      "Clear knowing",
      "Expression of the new"
    ]
  },
  {
    "number": 24,
    "name": "Rationalization",
    "center": "Ajna",
    "circuit": "Individual",
    "core": "Gate 24 is the energy of mental processing - going over and over a thought until it can be brought forward rationally. This gate processes mysteries. It sits with a question or a puzzle, running it through repeatedly, until something that was previously confused becomes comprehensible. The process can be slow and looping, but the outcome is genuine understanding arrived at through thorough individual processing.",
    "clean": "Gate 24 at its highest is the person who can take something complex or mysterious and make it rational without losing its essential nature. The patience to sit with not-knowing, to run it through repeatedly, to arrive at clarity - that is the gift. And once the clarity arrives, it is solid.",
    "listen": "Gate 24 songs have a quality of mental unraveling - you sense the artist working something out, slowly and honestly. Songs with meditative or repetitive qualities that feel like thinking made audible. Music that revisits a melodic or lyrical theme multiple times, arriving somewhere slightly different with each pass. Songs about mental loops, obsessive thought, the slow arrival of clarity after confusion.",
    "keywords": [
      "Rationalization",
      "Mental processing",
      "Mystery",
      "Repetition",
      "Understanding",
      "Individual thinking",
      "Loop to clarity",
      "Rationalizing",
      "Solving",
      "Patience"
    ]
  },
  {
    "number": 25,
    "name": "Innocence / Spirit Of Self",
    "center": "G Center",
    "circuit": "Individual",
    "core": "Gate 25 is the love of the spirit of the soul within you - and by extension, the love of the greater Spirit, whatever name or form that takes for you. This is the gate of the healer who needs no technique, the one who serves by being present in their own wholeness. There is an innocence to Gate 25 - a quality of being untouched by cynicism, of approaching life with a purity of heart that others find both rare and magnetic.",
    "clean": "Gate 25 at its highest has learned to maintain its innocence not by avoiding experience but by processing it without closing down. The heart stays open. The connection to Spirit remains alive. The healing presence it carries is offered freely because it is not something that can be depleted.",
    "listen": "Gate 25 songs carry a quality of spiritual love. Pure, wide, not directed at any particular object. Songs about the divine, about the love that holds everything, about the grace that arrives without being earned. Music that makes you feel innocent - not naive, but clean. Songs that feel like a prayer. The kind of song you listen to and feel your heart expanding without knowing exactly why.",
    "keywords": [
      "Innocence",
      "Spirit",
      "Divine love",
      "Healing",
      "Open heart",
      "Spiritual presence",
      "Purity",
      "Universal love",
      "Soul recognition",
      "Grace without condition"
    ]
  },
  {
    "number": 26,
    "name": "Trickster / Egoist",
    "center": "Heart/Ego",
    "circuit": "Tribal",
    "core": "Gate 26 is the deal-maker, the salesman, the trickster - the energy that knows how to get the most out of every situation. It carries the drive to negotiate, persuade, present, and position. At its best, this energy is marketing genius: it knows how to make something true sound appealing. At its worst, it slides into manipulation and exaggeration. Gate 26 lives in the Ego center, so its fuel is willpower, and it is applied in the service of tribal material exchange.",
    "clean": "Gate 26 at its highest is the master communicator who can make a genuinely good thing sound genuinely great. There is no deception here - the product or idea actually delivers. The skill is in making the value visible, in framing what is real in a way that lands. In this form, Gate 26 is the most effective marketing and sales energy in the chart.",
    "listen": "Gate 26 songs are persuasive. They want something from you and they are charming about it. Songs with a hook that you cannot escape. Music that knows it is good and is not being subtle about it. Songs about making deals, getting what you want, presenting your best face. There is a charisma to Gate 26 music - even when the content is emotionally complex, it is delivered with a kind of spin that makes it irresistible.",
    "keywords": [
      "Trickster",
      "Deal-making",
      "Persuasion",
      "Ego",
      "Tribal exchange",
      "Marketing",
      "Charm",
      "Positioning",
      "Negotiation",
      "Getting the most"
    ]
  },
  {
    "number": 27,
    "name": "Caring",
    "center": "Sacral",
    "circuit": "Tribal",
    "core": "Gate 27 is the energy of nourishment - the need to care for and be cared for within the tribe. It is directed inward toward family, group, and community. Gate 27 provides food, protection, attention, and the kind of tending that keeps a unit alive and cohesive. It is not generalized altruism - it is specific, tribal care directed at the people who belong to the same unit.",
    "clean": "Gate 27 at its highest provides care that is genuinely life-giving - to others and to itself. It knows who is in its care and tends to them with full attention and without martyrdom. The nourishment flows in both directions.",
    "listen": "Gate 27 songs are warm and caring in a specific, close way. Songs about taking care of people you love - not romantic love exclusively, but the love of care: making sure someone is fed, protected, okay. Songs that feel like home. Music that makes you want to check in on someone, to show up, to offer something tangible. Lullabies in any genre. The music of tending.",
    "keywords": [
      "Caring",
      "Nourishment",
      "Tribal support",
      "Protection",
      "Family",
      "Provision",
      "Love as action",
      "Tending",
      "Community",
      "Sacral care"
    ]
  },
  {
    "number": 28,
    "name": "Struggle / Risk",
    "center": "Spleen",
    "circuit": "Individual",
    "core": "Gate 28 is the energy of the struggle for meaning. Not external struggle - existential struggle. The question of what is actually worth the effort of a life. Gate 28 becomes wise through its encounters with difficulty, loss, and the moments when meaning seemed most absent. It is designed to risk - to put itself into situations that will test what it believes is worth fighting for. The shadow side of this is the fear that life has no meaning, which can become paralyzing when the gate is not moving toward actual risk.",
    "clean": "Gate 28 at its highest is the person who has been through something genuinely hard and come out the other side knowing what it was for. The wisdom they carry is not theoretical. It was earned. And they are willing to risk again, because they know the struggle is what makes meaning possible.",
    "listen": "Gate 28 songs deal in existential weight. Songs about what is worth living for, what is worth fighting for, the dark night that precedes the dawn. Not easy music. Songs that sit with suffering without trying to resolve it too quickly. Songs about wrestling with the big questions. Lyrically dense, emotionally honest, willing to go to the places that most music avoids. Also songs about choosing to risk - the decision to throw yourself into something you cannot guarantee will be worth it.",
    "keywords": [
      "Struggle",
      "Meaning",
      "Risk",
      "Existential",
      "Wisdom through pain",
      "Spleen instinct",
      "What's worth it",
      "Individual quest",
      "Fighting for purpose",
      "Dark before dawn"
    ]
  },
  {
    "number": 29,
    "name": "Perseverance / Yes",
    "center": "Sacral",
    "circuit": "Collective",
    "core": "Gate 29 is the energy of commitment - of saying yes and following through even without knowing how it ends. It is driven to persist where others quit, to push through the resistance that makes most people give up. This is not blind stubbornness. It is a Sacral-level faith in the process itself. Gate 29 commits to itself and to what it has said yes to, trusting that the destination will become clear through the doing.",
    "clean": "Gate 29 at its highest chooses its yeses carefully and then honors them completely. The commitment is real, the follow-through is steady, and the wisdom about when to release versus when to persist is rooted in genuine Sacral response rather than pressure.",
    "listen": "Gate 29 songs are about the long game. The decision to keep going. Songs about endurance, commitment, following through on something you cannot see the end of yet. Music that feels like a sustained effort - not exhausted, but resolute. Songs about saying yes to the process, to the work, to the relationship, to the journey even when you do not know where it leads. The energy of a long run, not a sprint.",
    "keywords": [
      "Yes",
      "Perseverance",
      "Commitment",
      "Following through",
      "Endurance",
      "Sacral response",
      "Saying yes",
      "Process",
      "Collective sustaining",
      "Persistence"
    ]
  },
  {
    "number": 30,
    "name": "Desire / Feelings",
    "center": "Solar Plexus",
    "circuit": "Collective",
    "core": "Gate 30 is the gate of desire - the feeling-based drive toward change and experience. This is the energy that recognizes an emotion pushing toward transformation and then conceptualizes it into a direction. Gate 30 is never free from desire, which is not a problem to be solved but a quality to be understood. The desire is what keeps it engaged with life. When the desire is honored rather than suppressed, it creates real, felt change.",
    "clean": "Gate 30 at its highest feels its desires fully and then works with them rather than against them. The wanting leads somewhere. The longing teaches something. The intensity of emotion is metabolized into understanding and, eventually, genuine change.",
    "listen": "Gate 30 songs burn. Songs about intense longing, burning desire, the ache of wanting something you cannot have or have not yet reached. These are emotional songs, but not soft ones - there is an intensity to them. Songs about being consumed by a feeling, about the desire that will not let you go. They are often some of the most emotionally gripping music you have in your library.",
    "keywords": [
      "Desire",
      "Longing",
      "Intensity",
      "Emotion",
      "Wanting",
      "Change",
      "Burning",
      "Collective feeling",
      "Transformation through desire",
      "Never free"
    ]
  },
  {
    "number": 31,
    "name": "Leading / Influence",
    "center": "Throat",
    "circuit": "Collective",
    "core": "Gate 31 is the voice of the leader - the natural authority that influences collective direction when it is recognized and invited. Gate 31 cannot assume leadership. It must be called into it. But when it is, the voice that emerges carries genuine authority that people want to orient themselves around. This is not the personal leadership of Gate 7 (G Center). This is Throat-level leadership - the word, the direction, the public voice.",
    "clean": "Gate 31 at its highest has learned the patience of its own authority. It waits until it is called, and when the call comes, the voice that answers is clear, confident, and genuinely useful to the collective. People follow not because they are obligated but because the direction is right.",
    "listen": "Gate 31 songs feel like someone stepping to the front. Songs where the artist is clearly a leader, where the voice carries weight, where listening feels like receiving direction. Collective anthems. Songs about stepping up. Music with a quality of \"follow me\" that is not arrogant but genuinely orienting. Songs that feel like they are moving a group somewhere.",
    "keywords": [
      "Leadership",
      "Influence",
      "Collective voice",
      "Authority",
      "Recognition",
      "Being called",
      "Direction",
      "Throat",
      "Natural leader",
      "\"Follow me\""
    ]
  },
  {
    "number": 32,
    "name": "Continuity",
    "center": "Spleen",
    "circuit": "Tribal",
    "core": "Gate 32 is the instinct for continuity - the ability to assess whether something can survive and adapt over time, and the drive to protect what can. This is a splenic gate, meaning its assessments are instantaneous and somatic rather than analytical. Gate 32 knows in its body whether something is worth preserving or whether it is already past its time. It is the tribal guardian of what is worth continuing.",
    "clean": "Gate 32 at its highest is the instinctive steward. It knows what is worth the effort of continuation and what is ready to be released, and it acts on that knowing without overthinking. The resources it protects are actually preserved by the quality of its discernment.",
    "listen": "Gate 32 songs have a sense of persistence and endurance. Songs about carrying on, about the instinct to survive and adapt, about the things that are worth preserving even when everything around them is shifting. There is a steadiness to Gate 32 music - not the fixed rhythm of Gate 5, but the instinct-level certainty of something that knows it belongs. Songs about tradition, legacy, the line that connects past to future.",
    "keywords": [
      "Continuity",
      "Instinct",
      "Adaptation",
      "Preservation",
      "Tribal endurance",
      "What's worth keeping",
      "Survival",
      "Carrying on",
      "Spleen knowing",
      "Generational"
    ]
  },
  {
    "number": 33,
    "name": "Privacy / Retreat",
    "center": "Throat",
    "circuit": "Collective",
    "core": "Gate 33 is the energy of retreat and private reflection. This gate requires solitude to do its work. It processes experience by withdrawing from it, sitting with what happened, and extracting the meaning before it is ready to share anything publicly. Gate 33 holds the power to reveal secrets - not because it seeks them out, but because the quality of reflection it brings to experience tends to uncover what was previously hidden. The privacy it seeks is not antisocial - it is necessary for the integration that makes collective sharing eventually possible.",
    "clean": "Gate 33 at its highest creates the rhythm of immersion and retreat that produces genuine wisdom. The solitude is honored, the reflection is thorough, and what eventually gets expressed from it has been refined in private into something worth sharing.",
    "listen": "Gate 33 songs feel private, like you caught the artist in a moment of honest solitude. Songs about needing space. Songs about the secrets that only come out in the quiet. Music that feels like it was made in a room by someone alone with their real thoughts. Songs about retreat as a sacred act rather than escape. Also songs that reveal something underneath - the deeper truth that only emerges after the noise stops.",
    "keywords": [
      "Privacy",
      "Retreat",
      "Reflection",
      "Solitude",
      "Secrets",
      "Integration",
      "Collective memory",
      "Processing",
      "Quiet wisdom",
      "Space"
    ]
  },
  {
    "number": 34,
    "name": "Power",
    "center": "Sacral",
    "circuit": "Individual",
    "core": "Gate 34 is raw Sacral power - the most energetically capable gate in the chart. This is the energy of the multitasker, the person who can do many things at once with enormous force, but only when responding to the right things. Gate 34 does not initiate - it responds, and when it does, the output is extraordinary. The power is vast and completely responsive, which means it cannot be directed by will alone. It works with the Sacral response, or it does not work at all in a sustainable way.",
    "clean": "Gate 34 at its highest is unstoppable in its right work. The power it brings to tasks that are genuine Sacral responses is extraordinary - productive, capable, multidimensional. And it knows when to stop, which is just as powerful as knowing when to go.",
    "listen": "Gate 34 songs feel powerful without trying to. Raw Sacral energy - the feeling of massive capability in motion. Songs that sound like they were made by someone with extraordinary energy, working at full output in the right direction. Physical, driving music. Songs about raw power, capability, the unstoppable feeling of moving correctly. Music that makes you feel like you could do anything.",
    "keywords": [
      "Power",
      "Sacral force",
      "Capability",
      "Raw energy",
      "Multitasking",
      "Response",
      "Unstoppable",
      "Individual momentum",
      "Physical drive",
      "Pure output"
    ]
  },
  {
    "number": 35,
    "name": "Change",
    "center": "Throat",
    "circuit": "Collective",
    "core": "Gate 35 is the energy of change through experience - and the sharing of that experience as story. Gate 35 senses when the wheel needs to turn, not logically but intuitively, and it moves toward new experience. When it shares the experiences it has lived through, it compels others to listen and inspires them toward their own change. The personal story is the vehicle. The change it creates is collective.",
    "clean": "Gate 35 at its highest is a storyteller whose lived experience becomes a catalyst. The stories it tells are not about performing a life - they are honest transmissions of what it is like to be human in a particular situation. Others hear them and feel moved, inspired, or less alone.",
    "listen": "Gate 35 songs are personal stories that carry universal resonance. The artist is clearly drawing from lived experience, and something about the specificity of that experience makes it land more broadly. Songs about things that happened to a real person that mirror what has happened to everyone. Music that inspires change not through instruction but through the recognition of \"yes, that is real, and look what they did with it.\"",
    "keywords": [
      "Change",
      "Experience",
      "Personal story",
      "Collective inspiration",
      "Throat expression",
      "Moving forward",
      "Sharing",
      "Novelty",
      "Storytelling",
      "Catalyst"
    ]
  },
  {
    "number": 36,
    "name": "Crisis",
    "center": "Solar Plexus",
    "circuit": "Collective",
    "core": "Gate 36 is the energy of emotional crisis as catalyst for change. It moves in a cycle: a crisis builds, which creates confusion and darkness, which forces an expression of what needs to change, which creates relief, which builds toward the next cycle. Gate 36 does not get to escape crisis - it is built to move through it. The gift is that every time it does, something that was dark becomes visible, and the change that results is real.",
    "clean": "Gate 36 at its highest is the expert at moving through emotional darkness toward light. Not because the crises stop, but because the cycle is understood. There is a dignity to the process - the willingness to go into the darkness knowing that the other side is real.",
    "listen": "Gate 36 songs feel heavy before they feel whole. Songs about breakdown that precede breakthrough. Music that takes you to a dark place not to strand you there but to move you through it. The emotional build of Gate 36 music is specific: crisis \u2192 intensity \u2192 release. Songs that feel cathartic in the truest sense - not just emotionally stimulating, but genuinely moving something through. Songs that you are grateful for afterward even if they were uncomfortable.",
    "keywords": [
      "Crisis",
      "Darkness \u2192 light",
      "Emotional cycle",
      "Breakthrough",
      "Collective experience",
      "Solar Plexus wave",
      "Catalyst",
      "Confusion before clarity",
      "Catharsis",
      "Moving through"
    ]
  },
  {
    "number": 37,
    "name": "Friendship / Harmony",
    "center": "Solar Plexus",
    "circuit": "Tribal",
    "core": "Gate 37 is the emotional heart of the tribe - the energy of belonging, family, and the bonds that create genuine community. This is not the generalized friendliness of social performance. It is the specific, felt experience of being part of a family - by blood or by choice. Gate 37 needs the warmth of its chosen tribe and contributes to the emotional cohesion that holds a group together. It deals in bonds, not transactions.",
    "clean": "Gate 37 at its highest is the heart of a chosen family - the one who makes everyone feel included, who holds the emotional thread of a community even through difficulty. The warmth it generates is not performance. It is a genuine felt sense of \"we belong to each other.\"",
    "listen": "Gate 37 songs feel like gathering. Songs about being with your people - not in an abstract way, but specifically, warmly, physically. Songs about friendship and family that carry actual intimacy rather than generic sentiment. Music that makes you want to be with people you love. The kind of song you play at a gathering. Songs that make you feel like you belong somewhere.",
    "keywords": [
      "Friendship",
      "Harmony",
      "Tribal bond",
      "Family",
      "Belonging",
      "Warmth",
      "Community",
      "Emotional connection",
      "\"We\"",
      "Chosen tribe"
    ]
  },
  {
    "number": 38,
    "name": "The Fighter",
    "center": "Root",
    "circuit": "Individual",
    "core": "Gate 38 is the energy of the fighter - specifically, the one who fights to discover what is worth struggling for. The purpose of Gate 38 is not victory over opponents. It is the pursuit of meaning through resistance. This gate does best when the odds are against it because the pressure is what activates the question underneath: \"What am I doing this for?\" When it finds an answer it believes in, it has more capacity to endure than almost any other gate.",
    "clean": "Gate 38 at its highest is a warrior who has found its cause. The fight is real, the stakes are real, the meaning is clear. This energy is extraordinary in service of something genuinely worth fighting for - it will not quit, it will not compromise the core thing, and its persistence creates transformation.",
    "listen": "Gate 38 songs feel like a battle cry with soul in it. Not the empty aggression of shadow fighting - the principled, grounded energy of someone who has decided what they are willing to go to war for. Songs about fighting through adversity, about being against the odds and choosing to keep going anyway. Songs about the warrior who knows what they are protecting.",
    "keywords": [
      "Fighter",
      "Meaning",
      "Struggle",
      "Purpose",
      "Against the odds",
      "Root pressure",
      "Individual quest",
      "Warrior spirit",
      "What's worth it",
      "Endurance"
    ]
  },
  {
    "number": 39,
    "name": "Provocation",
    "center": "Root",
    "circuit": "Individual",
    "core": "Gate 39 is the provocateur - the energy that creates disturbance in order to wake something up. Gate 39 is not here to fit in. It is here to agitate, to stir, to produce an emotional response that either moves the other person's spirit or reveals that the connection is not real. It is a Root gate, so the provocation comes with physical pressure. And it is Individual, so the purpose is deeply personal - not malicious, but activating.",
    "clean": "Gate 39 at its highest is the person whose edge activates something real in others. The provocation creates movement. People who can meet Gate 39 energy are moved by it toward something more alive. People who cannot meet it reveal their incompatibility, which is also useful information.",
    "listen": "Gate 39 songs have an agitating quality. Not uncomfortable in a bad way, but in a \"you cannot stay where you were\" way. Songs that unsettle your complacency. Music that pokes at something. Songs with an edge to them - energetically, lyrically, sonically. The kind of song that makes you want to do something or say something. Songs that dare you.",
    "keywords": [
      "Provocation",
      "Agitation",
      "Waking up",
      "Root pressure",
      "Individual stirring",
      "Spirit activation",
      "Edge",
      "Disruption",
      "\"I dare you\"",
      "Spiriting"
    ]
  },
  {
    "number": 40,
    "name": "Aloneness",
    "center": "Heart/Ego",
    "circuit": "Tribal",
    "core": "Gate 40 is the aloneness at the heart of community. It is part of the tribal channel of community, but it is the solitary pole - the energy that must step away from the group to rest and replenish. Gate 40 requires a balance between work and connection on one side, and genuine solitude on the other. Without the aloneness, it burns out. Without the community, the aloneness turns into isolation.",
    "clean": "Gate 40 at its highest knows exactly when to engage and when to retreat, and it honors both needs without guilt. The community it serves benefits from the fullness that the aloneness makes possible. The aloneness is enriched by the connection that follows it.",
    "listen": "Gate 40 songs feel like earned solitude. Songs about choosing to be alone, about the necessary space between connection. Songs about rest after effort, about the satisfaction of a closed door and a quiet room. Not lonely songs - alone songs. The distinction matters. These songs feel chosen, not forced. Music that makes you want to go be with yourself for a while.",
    "keywords": [
      "Aloneness",
      "Rest",
      "Solitude",
      "Balance",
      "Work and replenishment",
      "Tribal withdrawal",
      "Ego renewal",
      "\"I need space\"",
      "Community and retreat",
      "Will replenishment"
    ]
  },
  {
    "number": 41,
    "name": "Contraction",
    "center": "Root",
    "circuit": "Collective",
    "core": "Gate 41 is the gate of contraction - the pulling back before expansion. This is the Root Center's dreaming gate, always imagining a better world, fantasizing about what could be. Gate 41 does not create the new experience directly. It creates the emotional pressure toward novelty - the desire for something that has not existed yet - which then sets cycles in motion. It is often called the \"least\" gate in traditional Human Design (the start of the cycle), but this understates what it does: it seeds possibility.",
    "clean": "Gate 41 at its highest uses the contraction period as genuine preparation. The pulling back is purposeful. The fantasies it generates are seeds for real cycles of change. The emotional pressure it creates moves into cycles that produce actual experience.",
    "listen": "Gate 41 songs feel like longing for something that does not exist yet. Daydream music. Songs about the life that could be, the world that should exist, the version of yourself that is still becoming. There is a quality of fantasy that is not escape but preparation. Songs that seed possibility. Also songs that capture the feeling of pulling back before a leap - the held breath before expansion.",
    "keywords": [
      "Contraction",
      "Fantasy",
      "Dreaming",
      "Pulling back",
      "Preparation",
      "Emotional pressure",
      "Collective cycles",
      "Novelty",
      "Longing for the possible",
      "Starting point"
    ]
  },
  {
    "number": 42,
    "name": "Growth",
    "center": "Sacral",
    "circuit": "Collective",
    "core": "Gate 42 is the energy of completing growth cycles - of maximizing the potential in a process and then bringing it to closure. Gate 42 strongly desires to finish what it begins, and this makes it one of the most completion-oriented energies in the chart. It knows that closure is not failure - it is the necessary end of one cycle that makes space for the next. The difficulty is that its strong drive toward completion can lead to heavy expectations about outcomes.",
    "clean": "Gate 42 at its highest is the person who knows when something is done and can close it with grace. The cycle is completed fully - nothing left unfinished - and the release into the next phase is clean. The growth that happened is genuinely integrated.",
    "listen": "Gate 42 songs carry a sense of completion. Songs about finishing something, about arriving at the end of a phase. The musical structure often has a strong sense of resolution - things settling into place, the chord progression landing where it needs to. Songs about growth, about looking back at how far you have come. Songs that feel like endings that are also beginnings.",
    "keywords": [
      "Growth",
      "Completion",
      "Closure",
      "Cycles",
      "Finishing",
      "Maximizing potential",
      "Sacral commitment",
      "Collective growth",
      "\"I did it\"",
      "Release"
    ]
  },
  {
    "number": 43,
    "name": "Insight / Breakthrough",
    "center": "Ajna",
    "circuit": "Individual",
    "core": "Gate 43 is the energy of sudden knowing - the \"I know\" that arrives before the explanation. This is the individual insight that is ahead of its time, that comes without a logical chain of reasoning, and that is often dismissed by others until it proves out. Gate 43 must wait to be recognized before expressing its insights, not because the insights are wrong, but because without the context of recognition they cannot land.",
    "clean": "Gate 43 at its highest has the patience of genuine genius - it holds its knowing until the moment of recognition arrives, and when it does, what it shares creates real breakthroughs for the people who can receive it. The insight lands. The understanding that was not possible before is suddenly available.",
    "listen": "Gate 43 songs feel like a sudden understanding arriving. Songs with a clarity to them that feels sudden and complete. Music that makes you think \"I never heard it said like that before, but now I can't hear it any other way.\" The \"I know\" feeling. Songs with an awareness to them that is slightly out of time with the world around them - ahead of the curve.",
    "keywords": [
      "Insight",
      "Breakthrough",
      "Sudden knowing",
      "\"I know\"",
      "Ahead of time",
      "Individual awareness",
      "Ajna",
      "Recognition",
      "Downloading",
      "Genius"
    ]
  },
  {
    "number": 44,
    "name": "Alertness",
    "center": "Spleen",
    "circuit": "Tribal",
    "core": "Gate 44 is the instinctive assessment of patterns from the past to determine what is needed now. This gate reads history - not through memory but through the body's knowing of patterns. It is acutely aware of what other people are capable of, often knowing before they do what they will or will not be able to deliver. Its work is ensuring that material needs will be met for the tribe, and it does this through an instantaneous somatic reading of what the situation requires.",
    "clean": "Gate 44 at its highest is the one who sees clearly - who reads what is needed and what resources are available with accuracy and without emotional contamination. The tribal function it serves is genuine and essential. Its seeing keeps the tribe resourced and safe.",
    "listen": "Gate 44 songs carry a quality of pattern recognition. Songs that feel like they have seen this before. Music with a wisdom to it that is bodily rather than intellectual - not \"I figured it out\" but \"I remember this.\" Songs about survival, about recognizing danger before it materializes, about the instinct that tells you what this situation needs. Music with an alertness to it.",
    "keywords": [
      "Alertness",
      "Pattern recognition",
      "Past wisdom",
      "Instinct",
      "Tribal resource",
      "Spleen knowing",
      "Capability assessment",
      "Survival",
      "History",
      "Seeing what's needed"
    ]
  },
  {
    "number": 45,
    "name": "The Gatherer",
    "center": "Throat",
    "circuit": "Tribal",
    "core": "Gate 45 is the voice of the Gatherer - the tribal leader who brings people together around a shared resource, cause, or community. Gate 45 controls access to what it has gathered, whether material, informational, or community-based, and it organizes others around the use of those resources. This is the energy of the community builder, the steward of shared resources, the one who says \"we have this and here is how we share it.\"",
    "clean": "Gate 45 at its highest is genuinely generous with what it has built - while maintaining the integrity of the resource. It brings people together around something real, and the community that forms around its gathering is cohesive and nourished.",
    "listen": "Gate 45 songs feel like an invitation to gather. Songs that pull a community together - not for entertainment but for something that matters. Songs with a quality of \"come, there is something here for you.\" Music that feels like it is organizing something larger than a single listener. Communal, gathering-oriented, with a leader's voice at the center.",
    "keywords": [
      "Gathering",
      "Community",
      "Tribal leadership",
      "Resources",
      "Bringing together",
      "\"Come join\"",
      "Stewardship",
      "Voice of the tribe",
      "Collective resources",
      "Access"
    ]
  },
  {
    "number": 46,
    "name": "Serendipity / Determination",
    "center": "Of Self G Center",
    "circuit": "Collective",
    "core": "Gate 46 is the energy of being in the right place at the right time - not through planning but through embodied presence in the physical world. This gate loves the body, the flesh, the sensory experience of being alive in physical form. It connects to good fortune through its quality of presence - when it is fully inhabiting the moment and the body, the right things happen. Gate 46 teaches the perfection of the imperfect moment.",
    "clean": "Gate 46 at its highest is completely at home in physical existence. It enjoys the body, moves through space with ease, and the serendipity that follows is the natural result of being genuinely present to what the moment is offering.",
    "listen": "Gate 46 songs feel embodied. They live in the physical. Sensory, textured, alive. Songs that make you feel your body - not in a workout way, but in a \"I am here in this flesh and it is okay\" way. Songs about being physically present, about the good fortune that comes from showing up, about the body as a home. Music that makes you want to be in your body rather than in your head.",
    "keywords": [
      "Serendipity",
      "Body",
      "Physical presence",
      "Good fortune",
      "Embodiment",
      "Luck through presence",
      "Perfection in imperfection",
      "Flesh",
      "Sensing",
      "G Center love"
    ]
  },
  {
    "number": 47,
    "name": "Realization",
    "center": "Ajna",
    "circuit": "Collective",
    "core": "Gate 47 is the AHA gate - the epiphany. It takes the abstract fragments of experience (often those generated by Gate 64, Confusion) and assembles them into a whole. The process is not linear or logical. It happens in a moment of sudden synthesis, when disparate pieces that seemed disconnected reveal their underlying coherence. Before the AHA, everything feels confusing. After it, everything is clear. Gate 47 is the pivot point.",
    "clean": "Gate 47 at its highest has learned to sit with the confusion without needing it to resolve prematurely. It knows from experience that the AHA always comes - maybe not on a schedule, but reliably. The patience it develops makes the realization, when it arrives, even richer.",
    "listen": "Gate 47 songs carry that AHA quality. Music that feels like suddenly understanding something you have been circling for a long time. Songs where the chorus lands like a revelation. Music with a quality of \"and now I see it\" - things coming together, pieces clicking. Often emotionally light after something emotionally heavy. Songs that feel like relief combined with clarity.",
    "keywords": [
      "Realization",
      "AHA",
      "Epiphany",
      "Abstract to whole",
      "Clarity",
      "Collective insight",
      "Mental synthesis",
      "\"Now I see\"",
      "Puzzle complete",
      "Ajna"
    ]
  },
  {
    "number": 48,
    "name": "Depth",
    "center": "Spleen",
    "circuit": "Collective",
    "core": "Gate 48 is the energy of going deep - of looking at something in its full scope and working it with care and thoroughness. People with Gate 48 have an intuitive sense of beauty and design and a longing for things to be crafted with taste. This gate is the fear that it is not ready, that it does not know enough - but the depth it generates in response to that fear is what produces genuine mastery over time.",
    "clean": "Gate 48 at its highest has built a depth of understanding that is genuine and recognizable. The work it produces has a craftsmanship to it - it has been attended to at the level of detail. The fear of inadequacy has been the engine, not the brake.",
    "listen": "Gate 48 songs are sonically deep. Carefully crafted, layered, with a quality of beauty achieved through thoroughness. Songs where you hear something new every time you listen. Music that has been taken seriously - the production, the lyrics, the emotional construction. Songs about going deep, about taking the time to understand something fully, about the beauty that only emerges through patience.",
    "keywords": [
      "Depth",
      "Craftsmanship",
      "Beauty",
      "Thoroughness",
      "Intuition",
      "Collective wisdom",
      "Spleen knowing",
      "\"Not ready yet\" \u2192 mastery",
      "Detail",
      "Completeness"
    ]
  },
  {
    "number": 49,
    "name": "Revolution / Principles",
    "center": "Solar Plexus",
    "circuit": "Tribal",
    "core": "Gate 49 is the gate of revolution in service of principle. If a relationship, a community, or a situation violates the core principles this gate holds, it will push for change - sometimes dramatically. This is not revolution for its own sake. It is principle-driven upheaval. Gate 49 draws its lines clearly and will not tolerate consistent violations of what it believes is right. The emotion behind this is real and deep.",
    "clean": "Gate 49 at its highest draws its lines with clarity and compassion - standing firm on what matters without making everything a battle. The revolution it catalyzes is clean, purposeful, and in genuine service of the tribe's wellbeing.",
    "listen": "Gate 49 songs feel like they are drawing a line. Songs about standing for something, about refusing to accept what violates what you believe in. Principled anger. Principled love. Songs about ending something because it has crossed a line that cannot be uncrossed. Music with a quality of \"I have decided.\" Also songs about the emotional cost of that decision, and the clarity that follows it.",
    "keywords": [
      "Revolution",
      "Principles",
      "Drawing lines",
      "Tribal transformation",
      "Emotional upheaval",
      "Solar Plexus",
      "What I stand for",
      "Non-negotiable",
      "Deciding",
      "Righteous change"
    ]
  },
  {
    "number": 50,
    "name": "Values",
    "center": "Spleen",
    "circuit": "Tribal",
    "core": "Gate 50 is the energy of values and the rules that hold a tribe together. It instinctively knows what the tribe needs in order to function and thrive - not through analysis but through a somatic sense of what caring and cohesion actually require. Gate 50 is the keeper of the tribe's code. It maintains the standards that make mutual care possible.",
    "clean": "Gate 50 at its highest holds the values with a lightness that is not weakness. The code it maintains is alive, not rigid - it knows the difference between the values that are core and the forms they can take in different contexts. The care it provides is genuine, and it is also genuinely cared for in return.",
    "listen": "Gate 50 songs feel principled and warm at once. Songs about what we owe each other. About the codes of care that make community possible. About what is really right. Songs with a quality of moral clarity that does not feel preachy - it feels like wisdom. Songs about caring for the whole, about the rules that create safety.",
    "keywords": [
      "Values",
      "Tribal code",
      "Care",
      "Standards",
      "Cohesion",
      "Spleen instinct",
      "What we owe each other",
      "Responsibility",
      "Keeping the tribe",
      "Moral clarity"
    ]
  },
  {
    "number": 51,
    "name": "Shock / Initiation",
    "center": "Heart/Ego",
    "circuit": "Individual",
    "core": "Gate 51 is the energy of shock - the sudden, often startling action or statement that jolts others into connection with something bigger. Gate 51 is competitive and initiating. It can feel like it comes out of nowhere. The purpose of the shock is spiritual awakening - disrupting the habitual, the conditioned, the sleepy, so that what lies beneath can surface. Gate 51 does not apologize for its jarring quality. The jolt is the gift.",
    "clean": "Gate 51 at its highest is the initiator - the person who moves first, takes the risk, absorbs the shock of the unknown, and in doing so, opens the door for others. The shock it creates has a quality of \"wake up - there is more to life than the story you have been living.\"",
    "listen": "Gate 51 songs shock you, and it is good. Songs that jolt something loose. Music with unexpected choices - a lyric that comes out of nowhere and hits directly, a tonal shift that resets everything, a beat that breaks the pattern just when you were most settled. Songs that feel like initiation. Songs that leave you slightly different than you were before.",
    "keywords": [
      "Shock",
      "Initiation",
      "Competition",
      "Courage",
      "Disruption",
      "Spiritual awakening",
      "Ego",
      "Individual jolt",
      "\"Wake up\"",
      "First mover"
    ]
  },
  {
    "number": 52,
    "name": "Stillness",
    "center": "Root",
    "circuit": "Collective",
    "core": "Gate 52 is the stillness within the Root Center - the gate of inaction in the center of pressure. This is the energy of concentration achieved through genuine stillness. Not the stillness of nothing happening, but the stillness of everything in suspension before the right moment. Gate 52 has the capacity to sit very still and see the whole picture. This is highly creative energy - the kind of seeing that only becomes possible when the busy-ness stops.",
    "clean": "Gate 52 at its highest is the person who can find the still point inside the pressure. Not by suppressing the pressure, but by sitting inside it without reacting to it. The concentration they achieve in that stillness produces work that has a quality of wholeness - it was conceived in a space where the full picture could be seen.",
    "listen": "Gate 52 songs feel still. Not slow, necessarily, but internally still. Music that creates a concentrated quiet. Songs that make you stop moving, stop doing, and simply be with what is. Music for meditation, for genuine rest, for the kind of creative pause that precedes a breakthrough. Songs that feel like they are creating a container of calm inside a pressured world.",
    "keywords": [
      "Stillness",
      "Concentration",
      "Pause",
      "Seeing the whole",
      "Root inaction",
      "Creative stillness",
      "Rest as power",
      "Inner quiet",
      "Suspension",
      "Collective grounding"
    ]
  },
  {
    "number": 53,
    "name": "Beginnings / Starts",
    "center": "Root",
    "circuit": "Collective",
    "core": "Gate 53 is the gate of getting things started - the pressure to begin, to launch, to initiate a new cycle. This is not the individual initiation of the Manifestor's general nature. It is specifically the energy of the starting point in a collective developmental cycle. Gate 53 holds an enormous amount of pressure to begin new things, and when it is not starting something, it creates significant discomfort.",
    "clean": "Gate 53 at its highest uses its starting energy wisely - initiating cycles that have substance and handing off with consciousness once the beginning is complete. The launches it creates have a quality of genuine new cycles, not restarts of old patterns.",
    "listen": "Gate 53 songs feel like the energy of beginning. Songs you play at the start of something. Music with a quality of \"here we go\" - the excitement and the pressure of launching. Songs about new chapters, fresh starts, the moment before everything changes. The feeling of standing at the beginning of something large. Launch music. Opening music. The first day of something.",
    "keywords": [
      "Beginnings",
      "Starts",
      "Launch energy",
      "Initiation",
      "Pressure to begin",
      "New cycles",
      "Root pressure",
      "\"Here we go\"",
      "First step",
      "Collective development"
    ]
  },
  {
    "number": 54,
    "name": "Ambition",
    "center": "Root",
    "circuit": "Tribal",
    "core": "Gate 54 is the gate of ambition - big ambitions, grand vision, the limitless drive to succeed in the material world and climb to a higher position within the tribe or society. This is not a small, modest energy. Gate 54 wants to do things in a big or grand way. It is fueled by the desire for material and social achievement and it has the Root pressure to support that drive.",
    "clean": "Gate 54 at its highest directs its ambition in service of something larger than itself. The big vision, the material success, the elevated position - these are not ends in themselves but vehicles for creating something that genuinely benefits the tribe it is rising in service of.",
    "listen": "Gate 54 songs feel like empire-building. Songs about big dreams, grand visions, the desire to build something that lasts. Songs about wanting it all, about climbing, about the drive to go higher. Not humble songs. Songs that are unapologetic about wanting success, visibility, material achievement. Songs that make you feel your own ambition and give it permission to be as large as it actually is.",
    "keywords": [
      "Ambition",
      "Grand vision",
      "Material success",
      "Climbing",
      "Drive",
      "Tribal status",
      "\"I want it all\"",
      "Big energy",
      "Achievement",
      "Rising"
    ]
  },
  {
    "number": 55,
    "name": "Spirit / Abundance",
    "center": "Solar Plexus",
    "circuit": "Individual",
    "core": "Gate 55 is the gate of spirit and emotional abundance. This is not abundance in the material sense alone - it is the abundance of spirit, the fullness of a life that has real emotional depth. Gate 55 can feel stuck at times, as though the abundance it is reaching for is always slightly out of reach. But the stuckness is part of its process - the gate moves through periods of emptiness toward periods of genuine overflow.",
    "clean": "Gate 55 at its highest knows that spirit and abundance are the same thing, and that both arise through emotional honesty and depth rather than through external conditions. When this gate is in its highest expression, there is a quality of fullness to the person - not because everything is perfect, but because the spirit is genuinely fed.",
    "listen": "Gate 55 songs carry emotional depth that also has a quality of hope or abundance underneath. Not simple happy songs - songs that have been through something and come out with something. Songs about the spirit breaking through. Songs about the abundance that comes after the empty period. Music that feels emotionally full, layered, alive. Songs that make you feel rich in a way that has nothing to do with money.",
    "keywords": [
      "Spirit",
      "Abundance",
      "Emotional depth",
      "Individual feeling",
      "\"Getting through\"",
      "Overflow",
      "Solar Plexus richness",
      "Feeling full",
      "Spirit connection",
      "Breaking through"
    ]
  },
  {
    "number": 56,
    "name": "Stimulation / Storytelling",
    "center": "Throat",
    "circuit": "Collective",
    "core": "Gate 56 is the storyteller - the energy that takes ideas and past events and weaves them into compelling narratives that others can follow and learn from. This is the gate of the teacher who teaches through story, the communicator who makes abstract concepts concrete by putting them in the context of \"this is what happened.\" Gate 56 stimulates - it creates interest, sparks curiosity, and leaves people wanting to engage with what comes next.",
    "clean": "Gate 56 at its highest is the master storyteller whose narratives create genuine understanding. The stories are well-crafted and purposeful. They stimulate thinking and feeling in ways that serve the collective. People remember them.",
    "listen": "Gate 56 songs tell stories. They are narrative in the truest sense - you feel like you are being taken somewhere, being shown something, being told a story that matters. Songs with a quality of teaching through experience. Songs that stimulate your interest in a world, a time, a character, a situation. Music that is compelling in the same way a great story is compelling.",
    "keywords": [
      "Storytelling",
      "Stimulation",
      "Narrative",
      "Teaching through story",
      "Ideas expressed",
      "Collective sharing",
      "Memory",
      "Compelling",
      "\"Let me tell you\"",
      "Throat expression"
    ]
  },
  {
    "number": 57,
    "name": "Intuition / Clarity",
    "center": "Spleen",
    "circuit": "Individual",
    "core": "Gate 57 is the gate of penetrating intuitive insight - sometimes called the psychic gate. This is the spleen-level knowing of the now, a consistent access to intuition and awareness that goes beyond the merely physical. Gate 57 does not reason its way to its knowing. It simply knows. The clarity this gate generates is immediate and somatic, and it is always accurate in the moment it arrives.",
    "clean": "Gate 57 at its highest trusts the knowing immediately and acts on it without requiring proof. The insight that arrives is honored as valid data. The body's yes and no are listened to, and the quality of life that results from that listening is markedly different from the life that results from ignoring it.",
    "listen": "Gate 57 songs feel like the music already knows. Songs with a quality of effortless certainty - not arrogance, but knowing. Songs that feel like they arrived whole, that came through rather than being constructed. Music with an intuitive rightness that is hard to explain but immediately felt. Songs that trigger your own intuitive response - a chill, a recognition, a sudden clarity. Songs that feel psychic.",
    "keywords": [
      "Intuition",
      "Clarity",
      "\"I just know\"",
      "Psychic",
      "Spleen knowing",
      "Now awareness",
      "Beyond logic",
      "Individual insight",
      "Trust the knowing",
      "Somatic truth"
    ]
  },
  {
    "number": 58,
    "name": "Vitality / Joy Of Life",
    "center": "Root",
    "circuit": "Collective",
    "core": "Gate 58 is the energy of aliveness - the insatiable desire to make things better, to find joy in life, to challenge the status quo in service of improvement. This gate has a quality of genuine delight in existence that is rare and recognizable. When it is living its strategy, the people carrying Gate 58 have a smile that is not performative. They are genuinely glad to be alive, and that gladness creates an energy that improves everything it touches.",
    "clean": "Gate 58 at its highest is the person who is energized by the act of making things better, not depleted by it. The improvement comes from abundance, not anxiety. The joy is in the doing, not in the completion.",
    "listen": "Gate 58 songs feel joyful in a deep, earned way. Not surface-level happy songs - songs that carry a genuine love of being alive. Songs about vitality, aliveness, the pleasure of improvement. Music that makes you feel good not because it is telling you to feel good, but because the energy of it is genuinely alive. Songs with a quality of enthusiastic presence.",
    "keywords": [
      "Vitality",
      "Joy",
      "Aliveness",
      "Improvement",
      "Zest",
      "Collective uplift",
      "Root energy",
      "\"Let's make it better\"",
      "Genuine happiness",
      "Energizing"
    ]
  },
  {
    "number": 59,
    "name": "Intimacy / Sexuality",
    "center": "Sacral",
    "circuit": "Tribal",
    "core": "Gate 59 is the gateway to deep intimacy - sexual and otherwise. This is the energy of seduction, of coming together in the deepest possible way. It breaks down the barriers between people, creating closeness that goes beyond the social. Gate 59 is the tribal energy of genuine bonding - not the belonging of Gate 37, which is about community warmth, but the intimacy of actual merging between specific people.",
    "clean": "Gate 59 at its highest creates real, lasting intimacy. The connections it forms are genuine, deep, and transformative for everyone involved. The seduction is real not because of technique but because of authentic presence.",
    "listen": "Gate 59 songs feel intimate. Not just romantic - deeply, physically intimate. Songs about coming together, about the particular closeness of two people who have really let each other in. Songs with a quality of permission in them - \"come closer.\" Music that feels like being physically close to someone. Songs about desire that has real depth behind it, not just surface-level heat.",
    "keywords": [
      "Intimacy",
      "Sexuality",
      "Seduction",
      "Coming together",
      "Deep bonding",
      "Tribal connection",
      "Sacral desire",
      "\"Come closer\"",
      "Barriers dissolving",
      "Genuine closeness"
    ]
  },
  {
    "number": 60,
    "name": "Acceptance / Limitation",
    "center": "Root",
    "circuit": "Individual",
    "core": "Gate 60 is the energy of limitation as the prerequisite for a surge. This is the gate of acceptance - specifically, the acceptance of constraints that then releases a burst of momentum. Like a car engine starting, Gate 60 works in surges rather than sustained output. When it accepts the reality of its limitations, the pressure converts to forward motion. When it fights the limitations, nothing moves.",
    "clean": "Gate 60 at its highest has made peace with the constraints of its situation and has learned to use them as a launching point. The limitation is not a defeat - it is the necessary structure that channels the energy into a surge. Acceptance arrives not as resignation but as clarity.",
    "listen": "Gate 60 songs feel like a car starting. They carry that particular energy of compression before release - the moment when you accept what is true and then move forward from there. Songs about breaking through constraints, about the surge that happens after acceptance. Also songs about the limitation itself - the dignity of working within impossible conditions. \"Run Boy Run\" by Woodkid is the textbook example: Root pressure, individual initiation, burst of momentum from acceptance.",
    "keywords": [
      "Acceptance",
      "Limitation",
      "Surge",
      "Burst",
      "\"Go now\"",
      "Working within constraints",
      "Momentum",
      "Root pressure",
      "Individual launch",
      "Compression to release"
    ]
  },
  {
    "number": 61,
    "name": "Mystery",
    "center": "Head",
    "circuit": "Individual",
    "core": "Gate 61 is about reaching to know the unknowable - the \"why\" questions of existence that have no logical answer. This is the pressure of genuine mystery: not a puzzle to be solved, but a truth to be intuited, felt toward, circled rather than cracked. Gate 61 can reach for the unknown just for the pleasure of reaching. It is the Head Center pressure in its most individual, intuitive form - the longing for the answer to questions that language cannot contain.",
    "clean": "Gate 61 at its highest holds mystery with delight rather than anxiety. The unknowing is the point. The reaching is satisfying in itself. The questions this gate generates, when they move into the right channel, produce inspiration that is genuinely revelatory.",
    "listen": "Gate 61 songs feel like standing at the edge of something vast and unknowable. Songs that ask why. Songs about the mystery of consciousness, of existence, of the universe. Music that does not pretend to have answers. Songs that create a feeling of awe without resolving it into something tidy. Also music that feels like intuitive revelation - not logical clarity, but the sense of touching something that cannot be named.",
    "keywords": [
      "Mystery",
      "Why",
      "Unknowable",
      "Existential questions",
      "Wonder",
      "Head pressure",
      "Individual intuition",
      "Reaching",
      "\"What is this all for\"",
      "Awe"
    ]
  },
  {
    "number": 62,
    "name": "Details",
    "center": "Throat",
    "circuit": "Collective",
    "core": "Gate 62 is the energy of detail, precision, and practical organization. This gate has the capacity to organize complex things and provide the practical, step-by-step ways to implement them. Gate 62 speaks through names, facts, and concrete specifics. It makes the abstract actionable. Where other Throat gates speak in stories or declarations or visions, Gate 62 speaks in lists, procedures, and precise descriptions.",
    "clean": "Gate 62 at its highest is the essential organizer - the one who takes a vision and makes it real by breaking it into comprehensible, implementable steps. The detail it brings to expression is what makes the abstract accessible, the complex manageable, the possible actual.",
    "listen": "Gate 62 songs are precise. The words are exact. The production is meticulous. Songs where every detail seems to have been chosen with care. Music with a quality of information in it - not dry, but specific. Songs that feel organized, that move through their content with a kind of methodical beauty. Also songs about the precision of craft - the particular kind of love that goes into getting every detail right.",
    "keywords": [
      "Details",
      "Precision",
      "Organization",
      "Practical",
      "Step-by-step",
      "Naming",
      "Collective clarity",
      "\"Here's how\"",
      "Implementation",
      "Exactness"
    ]
  },
  {
    "number": 63,
    "name": "Doubt",
    "center": "Head",
    "circuit": "Collective",
    "core": "Gate 63 is the energy of logical questioning - the healthy skepticism that asks \"is this actually true?\" Its doubt is not personal or self-directed. It is pointed toward information, toward claims, toward ideas that need to be verified before they can be trusted as a basis for collective action. Gate 63 is the quality control of the logical mind - it questions so that the conclusions that emerge can be genuinely trusted.",
    "clean": "Gate 63 at its highest is a genuinely useful interrogator of ideas. The questions it asks improve what they touch. The doubt it generates is the friction that produces stronger conclusions. Others may find it challenging in the short term and deeply useful in the long term.",
    "listen": "Gate 63 songs carry a questioning energy. Songs that do not accept the easy answer. Music that sits with \"is this really true?\" Songs with an investigative quality - pushing against premises, looking for what is underneath. Songs about skepticism that is not cynicism but genuine inquiry. Also songs about the particular unease of not being sure - the productive discomfort of not yet knowing.",
    "keywords": [
      "Doubt",
      "Questioning",
      "Logical inquiry",
      "\"Is this true?\"",
      "Healthy skepticism",
      "Head pressure",
      "Collective quality control",
      "Verification",
      "Inquiry",
      "Testing"
    ]
  },
  {
    "number": 64,
    "name": "Confusion / Divine Confusion",
    "center": "Head",
    "circuit": "Collective",
    "core": "Gate 64 is the gate of abstract mental pressure - you can identify all the pieces of the puzzle, but putting them together in a coherent way requires a process that Gate 64 cannot complete alone. This is the beginning of the Collective Sensing stream, and it sits with the uncomfortable awareness that there is something important here, that all these fragments mean something, but the meaning has not yet assembled itself. Gate 64 generates the raw material for Gate 47's realizations.",
    "clean": "Gate 64 at its highest has learned to trust the confusion as part of the process. The pieces it is holding are going somewhere. The pressure is generative. What feels like a chaotic pile of fragments is actually the pre-condition for an insight that will emerge when the time is right.",
    "listen": "Gate 64 songs feel like being inside a complex thing that has not resolved yet. Songs with a quality of fragmentation - many pieces in motion, a picture that is forming but not yet complete. Music that creates the sensation of \"there is something here I almost understand.\" Atmospheric, layered, emotionally complex songs that feel like the inside of a powerful experience that has not yet been processed into meaning.",
    "keywords": [
      "Confusion",
      "Abstraction",
      "Fragments",
      "Mental pressure",
      "\"Something here\"",
      "Before the AHA",
      "Collective sensing",
      "Trust the process",
      "Dizzying",
      "Pieces forming"
    ]
  }
];
