(() => {
  'use strict';
  const root=document.getElementById('gym'), KEY='ma-authority-gym-v1';
  if(!root)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>root.querySelector('#'+id);
  let sessions=[], active=null, recognition=null;
  try { const data=JSON.parse(localStorage.getItem(KEY)||'[]'); if(Array.isArray(data))sessions=data.filter(s=>s&&typeof s.decision==='string'&&['Emotional','Splenic','Ego'].includes(s.authority)&&Array.isArray(s.reps)); } catch {}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(sessions));$('gym-status').textContent='Saved in this browser only.';}catch{$('gym-status').textContent='Browser storage is unavailable or full. Keep this tab open and print your WOD to keep it.';}}
  const field=(name,label)=>`<label>${label}<textarea name="${name}" maxlength="2000"></textarea></label>`;
  const choices=(name,label,items)=>`<fieldset><legend>${label}</legend><div class="gym-choices">${items.map((s,i)=>`<label><input type="radio" name="${name}" value="${esc(s)}" required><span>${esc(s)}</span></label>`).join('')}</div></fieldset>`;
  root.innerHTML=`<div class="gym-panel"><form id="gym-entry"><label>WHAT ARE YOU TRYING TO DECIDE?<textarea id="gym-decision" maxlength="1200" required placeholder="The actual decision you're fucking with."></textarea></label><label>What's your Authority?<select id="gym-authority" required><option value="">Choose yours</option><option>Emotional</option><option>Splenic</option><option>Ego</option><option value="unknown">I have no fucking idea</option></select></label><p id="gym-chart" hidden><a href="https://www.openhumandesign.com/" target="_blank" rel="noopener noreferrer">Check your chart at Open Human Design ↗</a>. Find your Authority, then come back. This gym is for Emotional, Splenic and Ego Manifestors.</p><label>CHOOSE YOUR WORKOUT<select id="gym-mode"><option>QUICK REP</option><option>HEAVY LIFT</option><option>AUTHORITY REPLAY</option></select></label><p>Quick Rep: a tiny decision, about 60 seconds of practice. Heavy Lift: more room for a bigger decision. Neither sets a deadline for clarity. Replay: notice a past decision.</p><button class="pg-btn pg-btn-green" type="submit">STEP INTO THE GYM</button></form><div id="gym-saved"></div><p class="gym-privacy">Decisions and completed reps are saved only in this browser, on this device. Anyone using it can read them. No account; nothing is sent to MA. Unsaved observations disappear when you leave. Delete your gym history below.</p><button id="gym-delete" type="button">CLEAR MY SHIT · ALL GYM HISTORY</button><p id="gym-status" role="status"></p></div><section id="gym-work" class="gym-panel" hidden tabindex="-1"></section><section id="gym-wod" hidden tabindex="-1"></section><p class="gym-rule">We don't know your answer. That's literally the fucking point. No advice is dispensed in this gym.</p>`;
  function saved(){ $('gym-saved').innerHTML=sessions.length?`<h2>BACK FOR ANOTHER REP?</h2>${sessions.map((s,i)=>`<button type="button" data-resume="${i}">${esc(s.decision)} <small>${esc(s.authority)} · ${s.reps.length} REPS · ${esc(s.mode)}</small></button>`).join('')}`:''; }
  function stopVoice(){if(recognition){const r=recognition;recognition=null;r.onresult=null;r.onerror=null;r.onend=null;r.abort();}}
  $('gym-authority').onchange=()=>{$('gym-chart').hidden=$('gym-authority').value!=='unknown';};
  $('gym-entry').onsubmit=e=>{e.preventDefault();if($('gym-authority').value==='unknown'){$('gym-chart').hidden=false;return;}const decision=$('gym-decision').value.trim();if(!decision){$('gym-decision').setCustomValidity('Write your decision first.');$('gym-decision').reportValidity();return;}active={decision,authority:$('gym-authority').value,mode:$('gym-mode').value,reps:[]};sessions.unshift(active);persist();saved();work();};
  $('gym-decision').oninput=()=> $('gym-decision').setCustomValidity('');
  $('gym-saved').onclick=e=>{const b=e.target.closest('[data-resume]');if(b){active=sessions[Number(b.dataset.resume)];work();}};
  $('gym-delete').onclick=()=>{if(!confirm('Delete every saved Authority Gym decision and rep from this browser?'))return;stopVoice();sessions=[];active=null;try{localStorage.removeItem(KEY);$('gym-status').textContent='All gym history deleted.';}catch{$('gym-status').textContent='Storage could not be cleared. Use your browser site-data settings to remove saved history.';}$('gym-work').hidden=true;$('gym-wod').hidden=true;$('gym-work').replaceChildren();$('gym-wod').replaceChildren();$('gym-entry').reset();$('gym-chart').hidden=true;saved();};
  function work(){stopVoice();$('gym-wod').hidden=true;const a=active.authority,replay=active.mode==='AUTHORITY REPLAY';let body='';
    if(replay)body=`<h2>AUTHORITY REPLAY</h2><p>Bring back a past decision. Describe what you remember without grading the outcome.</p>${field('signal',`What did your ${esc(a)} Authority feel or sound like?`)}${choices('followed','Did you follow it?',['Yes','No','Not sure'])}${field('learned','What do you recognize now?')}`;
    else if(a==='Emotional')body=`<h2>RIDE THE WAVE</h2><p>Cool. This is today's data. Not necessarily your answer. A high, a low, or a certainty score is not a verdict.</p>${choices('pull','How does this decision feel RIGHT NOW?',['FUCK YES','leaning yes','neutral','leaning no','absolutely fucking not'])}${choices('wave','Current emotional state',['High','Low','Somewhere between','Not sure'])}<label>Certainty right now<select name="certainty"><option>Not sure</option>${Array.from({length:11},(_,i)=>`<option>${i}/10</option>`).join('')}</select></label>${field('urgency','What feels urgent? Whose deadline is it?')}`;
    else if(a==='Splenic')body=`<h2>FIRST HIT · SPLEEN REP</h2><p><strong>DON'T THINK.</strong> Read your decision. What was the VERY FIRST thing you noticed?</p>${choices('signal','Capture the first signal',['Body sensation','Word','Image','Pull away','Pull toward','Quiet knowing','Nothing'])}<div id="gym-after-signal" hidden>${field('before','What happened before your brain started explaining it?')}<p>Nothing is a valid observation. We will not translate your signal into an answer.</p></div>`;
    else body=`<h2>SAY WHAT YOU WANT.</h2><p>3 rounds. Say that shit out loud. Hear yourself.</p><ol><li>Say what you want out loud.</li><li>Say the opposite out loud.</li><li>Notice which sounds or feels more true to your own ears. Unclear is allowed.</li></ol>${field('want','ROUND 1 · What I want')}${field('opposite','ROUND 2 · The opposite')}${field('hear','ROUND 3 · What I heard or felt')}<div id="gym-voice"></div><p>Typing is optional. The practice is saying it and hearing yourself; no recording is required.</p>`;
    $('gym-work').innerHTML=`<span class="pg-kicker">${esc(active.mode)} · ${esc(a)} · REP ${active.reps.length+1}</span><blockquote>${esc(active.decision)}</blockquote><form id="gym-rep">${body}<details ${active.mode==='HEAVY LIFT'?'open':''}><summary>MENTAL NOISE STRIPPER · OPTIONAL WARM-UP</summary>${field('should','What does my mind say I should do?')}${field('people','Who might be disappointed?')}${field('fear','Fear, proving, looking smart — what else is loud?')}<p>That is pressure you noticed. It is not an Authority answer.</p></details><button type="submit" class="pg-btn pg-btn-green">LOG THIS REP · TODAY'S WOD</button></form><div id="gym-history"></div>`;
    $('gym-work').hidden=false;$('gym-work').focus();
    if(a==='Splenic'&&!replay)$('gym-rep').onchange=e=>{if(e.target.name==='signal')$('gym-after-signal').hidden=false;};
    if(a==='Ego'&&!replay)voice();
    $('gym-history').innerHTML=active.reps.length?`<h3>YOUR PREVIOUS REPS</h3>${active.reps.map((r,i)=>`<button type="button" data-wod="${i}">REP ${i+1} · ${esc(new Date(r.date).toLocaleString())}</button>`).join('')}`:'';
    $('gym-history').onclick=e=>{const b=e.target.closest('[data-wod]');if(b)wod(active.reps[Number(b.dataset.wod)],Number(b.dataset.wod));};
    $('gym-rep').onsubmit=e=>{e.preventDefault();stopVoice();const observations=Object.fromEntries(new FormData(e.target));if(!Object.values(observations).some(v=>v.trim())){$('gym-status').textContent='Capture at least one observation first. “Nothing” or “not sure” counts.';return;}const rep={date:new Date().toISOString(),observations};active.reps.push(rep);persist();saved();wod(rep,active.reps.length-1);};
  }
  function voice(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return;$('gym-voice').innerHTML=`<p>Optional transcription may send audio to your browser's speech service. MA receives no audio. Edit anything misheard.</p><label>Transcribe into<select id="gym-voice-target"><option value="want">What I want</option><option value="opposite">The opposite</option><option value="hear">What I heard</option></select></label><button type="button" id="gym-mic">START TRANSCRIPTION</button><button type="button" id="gym-mic-stop">STOP</button><p id="gym-voice-status" role="status"></p>`;$('gym-mic').onclick=()=>{stopVoice();const target=$('gym-rep').elements[$('gym-voice-target').value];const r=new Recognition();recognition=r;r.interimResults=false;r.onresult=e=>{target.value=(target.value+' '+e.results[0][0].transcript).trim().slice(0,2000);};r.onerror=()=>{$('gym-voice-status').textContent='Transcription unavailable. You can keep speaking out loud and type your observations.';};r.onend=()=>{if(recognition===r){recognition=null;$('gym-voice-status').textContent+=' Microphone stopped.';}};try{r.start();$('gym-voice-status').textContent='Listening…';}catch{$('gym-voice-status').textContent='Unable to start. Speak out loud or type instead.';}};$('gym-mic-stop').onclick=stopVoice;}
  const labels={pull:'PULL RIGHT NOW',wave:'CURRENT WAVE',certainty:'CERTAINTY',urgency:'URGENCY',signal:'SIGNAL',before:'BEFORE THE EXPLANATION',want:'ROUND 1 · WHAT I WANT',opposite:'ROUND 2 · THE OPPOSITE',hear:'ROUND 3 · WHAT I HEARD',followed:'DID I FOLLOW IT?',learned:'WHAT I RECOGNIZE',should:'SHOULD',people:'DISAPPOINTMENT',fear:'OTHER NOISE'};
  function wod(rep,index){stopVoice();$('gym-work').hidden=true;const a=active.authority,o=rep.observations,replay=active.mode==='AUTHORITY REPLAY';const rows=keys=>keys.filter(k=>o[k]?.trim()).map(k=>`<div class="wod-row"><b>${labels[k]||esc(k)}</b><p>${esc(o[k])}</p></div>`).join('');const noise=['should','people','fear'];const rx=replay?'Notice what you recognize next time. No outcome grading.':a==='Emotional'?'Come back and run another rep when your emotional weather changes. No decision required in this gym.':a==='Splenic'?'Keep the first signal in your own words. Practice noticing again with another decision.':'Hear your own words again when you want to. You decide what they mean.';
    $('gym-wod').innerHTML=`<article class="wod-board"><header><span>TODAY'S WOD · ${esc(new Date(rep.date).toLocaleString())}</span><h2>AUTHORITY GYM</h2><strong>WOD: ${replay?'AUTHORITY REPLAY':{Emotional:'RIDE THE WAVE',Splenic:'FIRST HIT',Ego:'SAY THAT SHIT'}[a]}</strong></header><div class="wod-row"><b>TODAY'S LIFT</b><p>${esc(active.decision)}</p></div><div class="wod-row"><b>AUTHORITY / MODE</b><p>${a} / ${esc(active.mode)}</p></div><section><h3>WARM-UP</h3>${rows(noise)||'<p>Not logged this rep.</p>'}<small>Mental noise is separate from Authority.</small></section><section><h3>WORKOUT</h3>${rows(Object.keys(o).filter(k=>!noise.includes(k)))}</section><section><h3>TODAY'S REP</h3><p>☑ Captured my observations<br>☑ Logged rep ${index+1}</p></section><section><h3>RX · NEXT PRACTICE</h3><p>${rx}</p></section><footer>SCORE: CLARITY &gt; SPEED <span>REPS LOGGED: ${active.reps.length}</span></footer></article><div class="gym-actions"><button class="pg-btn pg-btn-green" id="gym-print">PRINT / SAVE PDF · TODAY'S WOD</button><button id="gym-again">ANOTHER REP · SAME DECISION</button><button id="gym-new">NEW DECISION</button></div>`;$('gym-wod').hidden=false;$('gym-wod').focus();$('gym-print').onclick=()=>window.print();$('gym-again').onclick=work;$('gym-new').onclick=()=>{stopVoice();$('gym-work').hidden=true;$('gym-wod').hidden=true;$('gym-entry').reset();$('gym-chart').hidden=true;$('gym-decision').focus();};}
  window.addEventListener('pagehide',()=>{stopVoice();$('gym-work').replaceChildren();$('gym-wod').replaceChildren();$('gym-entry').reset();});saved();
})();

