"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, Copy, Download, ExternalLink, Headphones, Library, LockKeyhole, Music2, RotateCcw, Sparkles, Trash2, Upload } from "lucide-react";

type Result = { number:number; name:string; center:string; circuit:string; reason:string; listen:string; compare:string; keywords:string[] };
type LibraryEntry = { id:string; date:string; song:string; artist:string; gate:number; gateName:string; center:string; circuit:string; evidence:string; feelings:string; notes:string };
const feelings = ["Defiant","Restless","Powerful","Tender","Private","Hungry","Hopeful","Pressured","Emotional","Provoked","Free","Afraid","Certain","Confused","Connected","Original","Intimate","Joyful"];
const centers = [["Head Center","Questions, inspiration or mental pressure"],["Ajna Center","Ideas, opinions or understanding"],["Throat Center","Voice, expression or action"],["G Center","Identity, love or direction"],["Ego Center","Willpower, value or control"],["Solar Plexus","Emotion, desire or intimacy"],["Spleen","Instinct, fear or survival"],["Sacral","Life force, sexuality or response"],["Root Center","Stress, pressure or momentum"],["","I have no idea yet"]];
const circuits = [["Individual","Different, disruptive, empowering or mutative"],["Collective","A pattern, story or shared experience"],["Tribal","Relationships, loyalty, needs or support"],["","I am not sure yet"]];
const SHEET_TEMPLATE="https://docs.google.com/spreadsheets/d/1U627DolJsqRZVqCX5vhEOrBbWQ0UA6FXYB9jQgoRFB8/copy";

export default function GateCoder() {
  const [unlocked,setUnlocked]=useState(false),[code,setCode]=useState(""),[codeError,setCodeError]=useState(""),[step,setStep]=useState(0);
  const [song,setSong]=useState(""),[artist,setArtist]=useState(""),[evidence,setEvidence]=useState(""),[selectedFeelings,setSelectedFeelings]=useState<string[]>([]),[ownWords,setOwnWords]=useState("");
  const [center,setCenter]=useState(""),[centerChosen,setCenterChosen]=useState(false),[circuit,setCircuit]=useState(""),[circuitChosen,setCircuitChosen]=useState(false);
  const [results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [library,setLibrary]=useState<LibraryEntry[]>([]),[showLibrary,setShowLibrary]=useState(false),[librarySearch,setLibrarySearch]=useState(""),[savedGate,setSavedGate]=useState<number|null>(null),[copiedId,setCopiedId]=useState<string|null>(null),[copiedGate,setCopiedGate]=useState<number|null>(null);
  const importRef=useRef<HTMLInputElement>(null);
  const canContinue=useMemo(()=>step===0?!!(song.trim()&&evidence.trim()):step===1?!!(selectedFeelings.length||ownWords.trim()):step===2?centerChosen:step===3?circuitChosen:true,[step,song,evidence,selectedFeelings,ownWords,centerChosen,circuitChosen]);
  useEffect(()=>{try{const saved=localStorage.getItem("ma_living_library");if(saved)setLibrary(JSON.parse(saved))}catch{}},[]);
  const filteredLibrary=useMemo(()=>{const q=librarySearch.toLowerCase().trim();return q?library.filter(e=>[e.song,e.artist,`gate ${e.gate}`,e.gateName,e.center,e.circuit,e.feelings].join(" ").toLowerCase().includes(q)):library},[library,librarySearch]);

  async function unlock(e:FormEvent){e.preventDefault();setCodeError("");const r=await fetch("/api/unlock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});if(r.ok)setUnlocked(true);else setCodeError("That access code did not work. Check the code included with your purchase.")}
  async function codeSong(){setLoading(true);setError("");const r=await fetch("/api/code-song",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({song,artist,evidence,feelings:selectedFeelings,ownWords,center,circuit})});if(r.status===401){setUnlocked(false);setStep(0);setLoading(false);return}if(!r.ok){setError("The coder hit a snag. Your answers are still here, so try again.");setLoading(false);return}const data=await r.json();setResults(data.results);setStep(4);setLoading(false)}
  function reset(){setStep(0);setSong("");setArtist("");setEvidence("");setSelectedFeelings([]);setOwnWords("");setCenter("");setCenterChosen(false);setCircuit("");setCircuitChosen(false);setResults([]);setError("")}
  function saveGate(result:Result){const entry:LibraryEntry={id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),song,artist,gate:result.number,gateName:result.name,center:result.center,circuit:result.circuit,evidence,feelings:[...selectedFeelings,ownWords].filter(Boolean).join(", "),notes:""};const next=[entry,...library];setLibrary(next);localStorage.setItem("ma_living_library",JSON.stringify(next));setSavedGate(result.number)}
  function removeEntry(id:string){const next=library.filter(e=>e.id!==id);setLibrary(next);localStorage.setItem("ma_living_library",JSON.stringify(next))}
  function entryText(e:LibraryEntry){return [e.date,e.song,e.artist,e.gate,e.gateName,e.center,e.circuit,e.feelings,e.evidence,e.notes].join("\t")}
  async function copyEntry(entry:LibraryEntry){await navigator.clipboard.writeText(entryText(entry));setCopiedId(entry.id);setTimeout(()=>setCopiedId(null),1600)}
  async function copyResult(result:Result){const entry:LibraryEntry={id:"",date:new Date().toISOString().slice(0,10),song,artist,gate:result.number,gateName:result.name,center:result.center,circuit:result.circuit,evidence,feelings:[...selectedFeelings,ownWords].filter(Boolean).join(", "),notes:""};await navigator.clipboard.writeText(entryText(entry));setCopiedGate(result.number);setTimeout(()=>setCopiedGate(null),1800)}
  function downloadLibrary(){const fields=["Date","Song","Artist","Gate","Gate Name","Center","Circuit","Feelings","Evidence","Notes"];const esc=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;const rows=library.map(e=>[e.date,e.song,e.artist,e.gate,e.gateName,e.center,e.circuit,e.feelings,e.evidence,e.notes].map(esc).join(","));const blob=new Blob([[fields.join(","),...rows].join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="my-human-design-music-library.csv";a.click();URL.revokeObjectURL(url)}
  function openSheetTemplate(){window.location.assign(SHEET_TEMPLATE)}
  function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=""}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=ch}row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
  async function importLibrary(file?:File){if(!file)return;const rows=parseCsv(await file.text());const data=rows[0]?.[0]?.toLowerCase()==="date"?rows.slice(1):rows;const incoming=data.filter(r=>r[1]||r[3]).map(r=>({id:crypto.randomUUID(),date:r[0]||new Date().toISOString().slice(0,10),song:r[1]||"Untitled song",artist:r[2]||"",gate:Number(String(r[3]).replace(/\D/g,""))||0,gateName:r[4]||"",center:r[5]||"",circuit:r[6]||"",feelings:r[7]||"",evidence:r[8]||"",notes:r[9]||""}));const next=[...incoming,...library];setLibrary(next);localStorage.setItem("ma_living_library",JSON.stringify(next));if(importRef.current)importRef.current.value=""}

  if(!unlocked)return <main className="min-h-screen bg-black text-white"><div className="noise"/><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><div className="brand">MANIFESTOR <span>ANONYMOUS</span></div><div className="pill"><LockKeyhole size={14}/> PAID COMPANION</div></header><section className="mx-auto grid max-w-6xl gap-10 px-5 pb-20 pt-8 sm:px-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center lg:pt-20"><div><p className="eyebrow">LEARN THE HUMAN DESIGN GATES THROUGH MUSIC</p><h1>STOP MEMORIZING.<br/><em>START HEARING.</em></h1><p className="lead">Turn what you hear in a song into three gate possibilities you can actually compare. The coder walks you from feeling to center, circuit and gate using the method inside your guide.</p><div className="feature-row"><span><Music2/> Code any song</span><span><Sparkles/> Compare 3 gates</span><span><BookOpen/> Use your guide better</span></div></div><form onSubmit={unlock} className="access-card"><div className="record-icon"><Headphones/></div><p className="step-label">BUYER ACCESS</p><h2>Open the Song-to-Gate Coder</h2><p>Your access code is included with your Learn the Gates Through Music purchase.</p><label htmlFor="code">ACCESS CODE</label><input id="code" value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter your code" autoComplete="off"/>{codeError&&<p className="error">{codeError}</p>}<button className="primary" type="submit">UNLOCK THE CODER <ArrowRight/></button><a className="buy-link" href="https://manifestoranonymous.com/gates-radio">Need access? Get the complete product →</a></form></section><div className="marquee"><span>LISTEN · NOTICE · CODE · BUILD · LISTEN · NOTICE · CODE · BUILD · LISTEN · NOTICE · CODE · BUILD</span></div></main>;

  return <main className="min-h-screen bg-black text-white"><div className="noise"/><header className="coder-header mx-auto flex max-w-5xl items-center justify-between px-5 py-5 sm:px-8"><div className="brand">MANIFESTOR <span>ANONYMOUS</span></div><div className="header-actions"><button className="text-button library-button" onClick={()=>setShowLibrary(v=>!v)}><Library size={15}/> THIS DEVICE <b>{library.length}</b></button><button className="text-button" onClick={()=>{setShowLibrary(false);reset()}}><RotateCcw size={15}/> NEW SONG</button></div></header><section className="mx-auto max-w-5xl px-5 pb-24 sm:px-8">{showLibrary?<LibraryView entries={filteredLibrary} total={library.length} search={librarySearch} setSearch={setLibrarySearch} download={downloadLibrary} copy={copyEntry} copiedId={copiedId} remove={removeEntry} close={()=>setShowLibrary(false)} importRef={importRef} importLibrary={importLibrary}/>:<><div className="tool-title"><p className="eyebrow">THE SONG-TO-GATE CODER</p><h2>{step<4?"Code what you actually hear.":`${song}${artist?` · ${artist}`:""}`}</h2>{step<4&&<p>There is no one objectively correct gate for a song. This tool helps you track your evidence and narrow the possibilities.</p>}</div>{step<4&&<div className="progress" aria-label={`Step ${step+1} of 4`}><span style={{width:`${(step+1)*25}%`}}/></div>}<div className="workspace">
  {step===0&&<div className="panel"><p className="step-label">01 · EXPERIENCE + EVIDENCE</p><h3>Start with the song, not a gate.</h3><div className="two-col"><label>SONG TITLE<input value={song} onChange={e=>setSong(e.target.value)} placeholder="What are you listening to?"/></label><label>ARTIST <span className="optional">OPTIONAL</span><input value={artist} onChange={e=>setArtist(e.target.value)} placeholder="Who is it by?"/></label></div><label>WHAT CREATED THE FEELING?<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Describe the lyric, beat, vocal shift, repetition, silence or overall tone that stood out. Do not paste full lyrics."/></label></div>}
  {step===1&&<div className="panel"><p className="step-label">02 · FEELING</p><h3>What did the song do to you?</h3><p className="helper">Choose as many as fit. Name your reaction, not the song&apos;s official meaning.</p><div className="chips">{feelings.map(f=><button type="button" key={f} className={selectedFeelings.includes(f)?"chip active":"chip"} onClick={()=>setSelectedFeelings(v=>v.includes(f)?v.filter(x=>x!==f):[...v,f])}>{selectedFeelings.includes(f)&&<Check size={14}/>} {f}</button>)}</div><label>YOUR OWN WORDS <span className="optional">OPTIONAL</span><input value={ownWords} onChange={e=>setOwnWords(e.target.value)} placeholder="Tense, aching, electric, homesick..."/></label></div>}
  {step===2&&<div className="panel"><p className="step-label">03 · CENTER</p><h3>What kind of energy is loudest?</h3><p className="helper">You do not need to know the centers yet. Choose the plain-language description that comes closest.</p><div className="option-grid">{centers.map(([value,label])=><button type="button" key={label} className={centerChosen&&center===value?"option active":"option"} onClick={()=>{setCenter(value);setCenterChosen(true)}}><strong>{value||"NOT SURE"}</strong><span>{label}</span></button>)}</div></div>}
  {step===3&&<div className="panel"><p className="step-label">04 · CIRCUIT</p><h3>How does the energy behave?</h3><p className="helper">Pick the closest pattern. “Not sure” is a valid answer.</p><div className="circuit-grid">{circuits.map(([value,label])=><button type="button" key={label} className={circuitChosen&&circuit===value?"option active":"option"} onClick={()=>{setCircuit(value);setCircuitChosen(true)}}><strong>{value||"NOT SURE"}</strong><span>{label}</span></button>)}</div></div>}
  {step===4&&<div className="results-panel"><div className="result-intro"><div><p className="step-label">YOUR THREE GATE POSSIBILITIES</p><h3>Choose what belongs in your library.</h3></div><button className="outline" onClick={()=>window.print()}>PRINT RESULTS</button></div><div className="permanent-library-callout"><div><strong>KEEP IT PERMANENT</strong><p>Make your own Google Sheet once. Then copy any gate result directly into its next blank row.</p></div><button type="button" onClick={openSheetTemplate}>GET MY GOOGLE SHEETS TEMPLATE <ExternalLink/></button></div><div className="results">{results.map((r,i)=><article className={i===0?"result-card top":"result-card"} key={r.number}><div className="rank">{i===0?"STRONGEST MATCH":`COMPARE #${i+1}`}</div><div className="gate-line"><span>GATE {r.number}</span><h4>{r.name}</h4></div><div className="metadata"><span>{r.center}</span><span>{r.circuit} circuit</span></div><p className="reason">{r.reason}</p><div className="listen"><strong>WHAT TO LISTEN FOR</strong><p>{r.listen}</p></div><div className="compare"><strong>COMPARE IT</strong><p>{r.compare}</p></div><div className="keywords">{r.keywords.slice(0,6).map(k=><span key={k}>{k}</span>)}</div><p className="page-note">Open Gate {r.number} in your reference guide and record what fits on the Song Coding Sheet.</p><div className="result-save-actions"><button className="sheet-copy-button" onClick={()=>copyResult(r)}>{copiedGate===r.number?<><Check/> COPIED. PASTE INTO YOUR SHEET</>:<><Copy/> COPY GATE {r.number} FOR GOOGLE SHEETS</>}</button><button className={savedGate===r.number?"save-button saved":"save-button"} onClick={()=>saveGate(r)}>{savedGate===r.number?<><Check/> SAVED ON THIS DEVICE</>:<><Library/> ALSO SAVE ON THIS DEVICE</>}</button></div></article>)}</div><button className="primary restart" onClick={reset}>CODE ANOTHER SONG <RotateCcw/></button></div>}
  </div>{step<4&&<div className="nav-buttons"><button className="back" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft/> BACK</button>{step<3?<button className="primary" disabled={!canContinue} onClick={()=>setStep(s=>s+1)}>CONTINUE <ArrowRight/></button>:<button className="primary" disabled={!canContinue||loading} onClick={codeSong}>{loading?"CODING...":"FIND MY GATES"} <Sparkles/></button>}</div>}{error&&<p className="error center-error">{error}</p>}</>}</section></main>;
}

function LibraryView({entries,total,search,setSearch,download,copy,copiedId,remove,close,importRef,importLibrary}:{entries:LibraryEntry[];total:number;search:string;setSearch:(v:string)=>void;download:()=>void;copy:(e:LibraryEntry)=>void;copiedId:string|null;remove:(id:string)=>void;close:()=>void;importRef:React.RefObject<HTMLInputElement|null>;importLibrary:(f?:File)=>void}){
  return <div className="library-view"><div className="device-warning"><strong>LIBRARY ON THIS DEVICE</strong><span>This is a working copy, not your permanent library. Clearing browser data can erase it.</span></div><div className="library-hero"><div><p className="eyebrow">THIS DEVICE</p><h2>{total} {total===1?"SONG":"SONGS"} CODED</h2><p>Use your Google Sheet as the permanent home for your music library.</p></div><button type="button" className="primary template-link" onClick={()=>window.location.assign(SHEET_TEMPLATE)}>GET GOOGLE SHEETS TEMPLATE <ExternalLink/></button></div><div className="library-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search songs, artists or gates..."/><button className="outline" onClick={download} disabled={!total}><Download/> DOWNLOAD BACKUP</button><button className="outline" onClick={()=>importRef.current?.click()}><Upload/> RESTORE BACKUP</button><input ref={importRef} hidden type="file" accept=".csv,text/csv" onChange={e=>importLibrary(e.target.files?.[0])}/><button className="outline" onClick={close}>BACK TO CODER</button></div>{!total?<div className="empty-library"><Library/><h3>This device library is empty.</h3><p>Code a song, compare the results, then save the gate that fits.</p><button className="primary" onClick={close}>CODE MY FIRST SONG <ArrowRight/></button></div>:<div className="library-list">{entries.map(e=><article className="library-entry" key={e.id}><div className="library-date">{e.date}</div><div className="library-main"><h3>{e.song}</h3><p>{e.artist||"Artist not added"}</p><div className="metadata"><span>Gate {e.gate} · {e.gateName}</span><span>{e.center}</span><span>{e.circuit}</span></div><dl><dt>WHAT I HEARD</dt><dd>{e.evidence}</dd><dt>WHAT I FELT</dt><dd>{e.feelings||"Not recorded"}</dd></dl></div><div className="entry-actions"><button onClick={()=>copy(e)}><Copy/>{copiedId===e.id?"COPIED":"COPY FOR SHEETS"}</button><button className="delete" onClick={()=>remove(e.id)} aria-label={`Delete ${e.song}`}><Trash2/> DELETE</button></div></article>)}</div>}<div className="sheet-help"><strong>YOUR GOOGLE SHEET IS THE PERMANENT COPY</strong><p>Copy each chosen gate and paste it into the next blank row. Use Download Backup and Restore Backup only for the library stored on this device.</p></div></div>
}
